// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// Metadata for a stitched ad.
public struct AdStitchDetail: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. The ad break ID of the processed ad.
  public var adBreakId: Swift.String = Swift.String()

  /// Required. The ad ID of the processed ad.
  public var adId: Swift.String = Swift.String()

  /// Required. The time offset of the processed ad.
  public var adTimeOffset: GoogleWKT.Duration? = nil

  /// Optional. Indicates the reason why the ad has been skipped.
  public var skipReason: Swift.String = Swift.String()

  /// Optional. The metadata of the chosen media file for the ad.
  public var media: [Swift.String: GoogleWKT.Value] = [:]

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `AdStitchDetail`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AdStitchDetail().with { $0.adBreakId = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let adBreakId = CodingKeys(stringValue: "adBreakId")
    static let adId = CodingKeys(stringValue: "adId")
    static let adTimeOffset = CodingKeys(stringValue: "adTimeOffset")
    static let skipReason = CodingKeys(stringValue: "skipReason")
    static let media = CodingKeys(stringValue: "media")

    static let _knownKeys: Set<Swift.String> = [
      "adBreakId",
      "adId",
      "adTimeOffset",
      "skipReason",
      "media",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .adBreakId) {
      self.adBreakId = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .adId) {
      self.adId = value
    }
    self.adTimeOffset = try container.decodeIfPresent(
      GoogleWKT.Duration.self, forKey: .adTimeOffset)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .skipReason) {
      self.skipReason = value
    }
    if let value = try container.decodeIfPresent(
      [Swift.String: GoogleWKT.Value].self, forKey: .media)
    {
      self.media = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.adBreakId, forKey: .adBreakId)
    try container.encode(self.adId, forKey: .adId)
    try container.encodeIfPresent(self.adTimeOffset, forKey: .adTimeOffset)
    try container.encode(self.skipReason, forKey: .skipReason)
    try container.encode(self.media, forKey: .media)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.video.stitcher.v1.AdStitchDetail"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
