// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Configuration for a CDN key. Used by the Video Stitcher
/// to sign URIs for fetching video manifests and signing
/// media segments for playback.
public struct CdnKey: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// The resource name of the CDN key, in the form of
  /// `projects/{project}/locations/{location}/cdnKeys/{id}`.
  /// The name is ignored when creating a CDN key.
  public var name: Swift.String = Swift.String()

  /// The hostname this key applies to.
  public var hostname: Swift.String = Swift.String()

  /// Configuration associated with the CDN key.
  public var cdnKeyConfig: OneOf_CdnKeyConfig? = nil

  /// Initialize a new instance of `CdnKey`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CdnKey().with { $0.googleCdnKey = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case googleCdnKey = "googleCdnKey"
    case akamaiCdnKey = "akamaiCdnKey"
    case mediaCdnKey = "mediaCdnKey"
    case name = "name"
    case hostname = "hostname"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.name = try container.decode(Swift.String.self, forKey: .name)
    self.hostname = try container.decode(Swift.String.self, forKey: .hostname)

    var cdnKeyConfig: OneOf_CdnKeyConfig? = nil
    let cdnKeyConfigCheckAndSet = {
      if cdnKeyConfig != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'cdnKeyConfig'"))
      }
      cdnKeyConfig = $0
    }
    if let googleCdnKey = try container.decodeIfPresent(GoogleCdnKey?.self, forKey: .googleCdnKey) {
      try cdnKeyConfigCheckAndSet(.googleCdnKey(googleCdnKey))
    }
    if let akamaiCdnKey = try container.decodeIfPresent(AkamaiCdnKey?.self, forKey: .akamaiCdnKey) {
      try cdnKeyConfigCheckAndSet(.akamaiCdnKey(akamaiCdnKey))
    }
    if let mediaCdnKey = try container.decodeIfPresent(MediaCdnKey?.self, forKey: .mediaCdnKey) {
      try cdnKeyConfigCheckAndSet(.mediaCdnKey(mediaCdnKey))
    }
    self.cdnKeyConfig = cdnKeyConfig
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.hostname, forKey: .hostname)

    if let choice = self.cdnKeyConfig {
      switch choice {
      case .googleCdnKey(let value):
        try container.encode(value, forKey: .googleCdnKey)
      case .akamaiCdnKey(let value):
        try container.encode(value, forKey: .akamaiCdnKey)
      case .mediaCdnKey(let value):
        try container.encode(value, forKey: .mediaCdnKey)
      }
    }
  }

  /// Configuration associated with the CDN key.
  public enum OneOf_CdnKeyConfig: Codable, Equatable, Sendable {
    /// The configuration for a Google Cloud CDN key.
    indirect case googleCdnKey(GoogleCdnKey?)
    /// The configuration for an Akamai CDN key.
    indirect case akamaiCdnKey(AkamaiCdnKey?)
    /// The configuration for a Media CDN key.
    indirect case mediaCdnKey(MediaCdnKey?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.video.stitcher.v1.CdnKey"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
