// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Metadata for a companion.
public struct Companion: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The API necessary to communicate with the creative if available.
  public var apiFramework: Swift.String = Swift.String()

  /// The pixel height of the placement slot for the intended creative.
  public var heightPx: Swift.Int32 = Swift.Int32()

  /// The pixel width of the placement slot for the intended creative.
  public var widthPx: Swift.Int32 = Swift.Int32()

  /// The pixel height of the creative.
  public var assetHeightPx: Swift.Int32 = Swift.Int32()

  /// The maximum pixel height of the creative in its expanded state.
  public var expandedHeightPx: Swift.Int32 = Swift.Int32()

  /// The pixel width of the creative.
  public var assetWidthPx: Swift.Int32 = Swift.Int32()

  /// The maximum pixel width of the creative in its expanded state.
  public var expandedWidthPx: Swift.Int32 = Swift.Int32()

  /// The ID used to identify the desired placement on a publisher's page.
  /// Values to be used should be discussed between publishers and
  /// advertisers.
  public var adSlotId: Swift.String = Swift.String()

  /// The list of tracking events for the companion.
  public var events: [Event] = []

  /// Ad resource associated with the companion ad.
  public var adResource: OneOf_AdResource? = nil

  /// Initialize a new instance of `Companion`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Companion().with { $0.iframeAdResource = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case iframeAdResource = "iframeAdResource"
    case staticAdResource = "staticAdResource"
    case htmlAdResource = "htmlAdResource"
    case apiFramework = "apiFramework"
    case heightPx = "heightPx"
    case widthPx = "widthPx"
    case assetHeightPx = "assetHeightPx"
    case expandedHeightPx = "expandedHeightPx"
    case assetWidthPx = "assetWidthPx"
    case expandedWidthPx = "expandedWidthPx"
    case adSlotId = "adSlotId"
    case events = "events"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.apiFramework = try container.decode(Swift.String.self, forKey: .apiFramework)
    self.heightPx = try container.decode(Swift.Int32.self, forKey: .heightPx)
    self.widthPx = try container.decode(Swift.Int32.self, forKey: .widthPx)
    self.assetHeightPx = try container.decode(Swift.Int32.self, forKey: .assetHeightPx)
    self.expandedHeightPx = try container.decode(Swift.Int32.self, forKey: .expandedHeightPx)
    self.assetWidthPx = try container.decode(Swift.Int32.self, forKey: .assetWidthPx)
    self.expandedWidthPx = try container.decode(Swift.Int32.self, forKey: .expandedWidthPx)
    self.adSlotId = try container.decode(Swift.String.self, forKey: .adSlotId)
    self.events = try container.decode([Event].self, forKey: .events)

    var adResource: OneOf_AdResource? = nil
    let adResourceCheckAndSet = {
      if adResource != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'adResource'"))
      }
      adResource = $0
    }
    if let iframeAdResource = try container.decodeIfPresent(
      IframeAdResource?.self, forKey: .iframeAdResource)
    {
      try adResourceCheckAndSet(.iframeAdResource(iframeAdResource))
    }
    if let staticAdResource = try container.decodeIfPresent(
      StaticAdResource?.self, forKey: .staticAdResource)
    {
      try adResourceCheckAndSet(.staticAdResource(staticAdResource))
    }
    if let htmlAdResource = try container.decodeIfPresent(
      HtmlAdResource?.self, forKey: .htmlAdResource)
    {
      try adResourceCheckAndSet(.htmlAdResource(htmlAdResource))
    }
    self.adResource = adResource
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.apiFramework, forKey: .apiFramework)
    try container.encode(self.heightPx, forKey: .heightPx)
    try container.encode(self.widthPx, forKey: .widthPx)
    try container.encode(self.assetHeightPx, forKey: .assetHeightPx)
    try container.encode(self.expandedHeightPx, forKey: .expandedHeightPx)
    try container.encode(self.assetWidthPx, forKey: .assetWidthPx)
    try container.encode(self.expandedWidthPx, forKey: .expandedWidthPx)
    try container.encode(self.adSlotId, forKey: .adSlotId)
    try container.encode(self.events, forKey: .events)

    if let choice = self.adResource {
      switch choice {
      case .iframeAdResource(let value):
        try container.encode(value, forKey: .iframeAdResource)
      case .staticAdResource(let value):
        try container.encode(value, forKey: .staticAdResource)
      case .htmlAdResource(let value):
        try container.encode(value, forKey: .htmlAdResource)
      }
    }
  }

  /// Ad resource associated with the companion ad.
  public enum OneOf_AdResource: Codable, Equatable, Sendable {
    /// The IFrame ad resource associated with the companion ad.
    indirect case iframeAdResource(IframeAdResource?)
    /// The static ad resource associated with the companion ad.
    indirect case staticAdResource(StaticAdResource?)
    /// The HTML ad resource associated with the companion ad.
    indirect case htmlAdResource(HtmlAdResource?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.video.stitcher.v1.Companion"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
