// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Request message for VideoStitcherService.createCdnKey.
public struct CreateCdnKeyRequest: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. The project in which the CDN key should be created, in the form
  /// of `projects/{project_number}/locations/{location}`.
  public var parent: Swift.String = Swift.String()

  /// Required. The CDN key resource to create.
  public var cdnKey: CdnKey? = nil

  /// Required. The ID to use for the CDN key, which will become the final
  /// component of the CDN key's resource name.
  ///
  /// This value should conform to RFC-1034, which restricts to
  /// lower-case letters, numbers, and hyphen, with the first character a
  /// letter, the last a letter or a number, and a 63 character maximum.
  public var cdnKeyId: Swift.String = Swift.String()

  /// Initialize a new instance of `CreateCdnKeyRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CreateCdnKeyRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.video.stitcher.v1.CreateCdnKeyRequest"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
