// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Describes an event and a trigger URI.
public struct Event: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Describes the event that occurred.
  public var type: Event.EventType = Event.EventType()

  /// The URI to trigger for this event.
  public var uri: Swift.String = Swift.String()

  /// The ID of the event.
  public var id: Swift.String = Swift.String()

  /// The offset in seconds if the event type is `PROGRESS`.
  public var offset: GoogleCloudWKT.Duration? = nil

  /// Initialize a new instance of `Event`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Event().with { $0.type = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Describes the event that occurred.
  public enum EventType: Codable, Equatable, Sendable {
    /// The event type is unspecified.
    case unspecified
    /// First frame of creative ad viewed.
    case creativeView
    /// Creative ad started.
    case start
    /// Start of an ad break.
    case breakStart
    /// End of an ad break.
    case breakEnd
    /// Impression.
    case impression
    /// First quartile progress.
    case firstQuartile
    /// Midpoint progress.
    case midpoint
    /// Third quartile progress.
    case thirdQuartile
    /// Ad progress completed.
    case complete
    /// Specific progress event with an offset.
    case progress
    /// Player muted.
    case mute
    /// Player unmuted.
    case unmute
    /// Player paused.
    case pause
    /// Click event.
    case click
    /// Click-through event.
    case clickThrough
    /// Player rewinding.
    case rewind
    /// Player resumed.
    case resume
    /// Error event.
    case error
    /// Ad expanded to a larger size.
    case expand
    /// Ad collapsed to a smaller size.
    case collapse
    /// Non-linear ad closed.
    case close
    /// Linear ad closed.
    case closeLinear
    /// Ad skipped.
    case skip
    /// Accept invitation event.
    case acceptInvitation
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .creativeView: return 1
      case .start: return 2
      case .breakStart: return 3
      case .breakEnd: return 4
      case .impression: return 5
      case .firstQuartile: return 6
      case .midpoint: return 7
      case .thirdQuartile: return 8
      case .complete: return 9
      case .progress: return 10
      case .mute: return 11
      case .unmute: return 12
      case .pause: return 13
      case .click: return 14
      case .clickThrough: return 15
      case .rewind: return 16
      case .resume: return 17
      case .error: return 18
      case .expand: return 21
      case .collapse: return 22
      case .close: return 24
      case .closeLinear: return 25
      case .skip: return 26
      case .acceptInvitation: return 27
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "EVENT_TYPE_UNSPECIFIED"
      case .creativeView: return "CREATIVE_VIEW"
      case .start: return "START"
      case .breakStart: return "BREAK_START"
      case .breakEnd: return "BREAK_END"
      case .impression: return "IMPRESSION"
      case .firstQuartile: return "FIRST_QUARTILE"
      case .midpoint: return "MIDPOINT"
      case .thirdQuartile: return "THIRD_QUARTILE"
      case .complete: return "COMPLETE"
      case .progress: return "PROGRESS"
      case .mute: return "MUTE"
      case .unmute: return "UNMUTE"
      case .pause: return "PAUSE"
      case .click: return "CLICK"
      case .clickThrough: return "CLICK_THROUGH"
      case .rewind: return "REWIND"
      case .resume: return "RESUME"
      case .error: return "ERROR"
      case .expand: return "EXPAND"
      case .collapse: return "COLLAPSE"
      case .close: return "CLOSE"
      case .closeLinear: return "CLOSE_LINEAR"
      case .skip: return "SKIP"
      case .acceptInvitation: return "ACCEPT_INVITATION"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:EventType/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "EVENT_TYPE_UNSPECIFIED": self = .unspecified
      case "CREATIVE_VIEW": self = .creativeView
      case "START": self = .start
      case "BREAK_START": self = .breakStart
      case "BREAK_END": self = .breakEnd
      case "IMPRESSION": self = .impression
      case "FIRST_QUARTILE": self = .firstQuartile
      case "MIDPOINT": self = .midpoint
      case "THIRD_QUARTILE": self = .thirdQuartile
      case "COMPLETE": self = .complete
      case "PROGRESS": self = .progress
      case "MUTE": self = .mute
      case "UNMUTE": self = .unmute
      case "PAUSE": self = .pause
      case "CLICK": self = .click
      case "CLICK_THROUGH": self = .clickThrough
      case "REWIND": self = .rewind
      case "RESUME": self = .resume
      case "ERROR": self = .error
      case "EXPAND": self = .expand
      case "COLLAPSE": self = .collapse
      case "CLOSE": self = .close
      case "CLOSE_LINEAR": self = .closeLinear
      case "SKIP": self = .skip
      case "ACCEPT_INVITATION": self = .acceptInvitation
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:EventType/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .creativeView
      case 2: self = .start
      case 3: self = .breakStart
      case 4: self = .breakEnd
      case 5: self = .impression
      case 6: self = .firstQuartile
      case 7: self = .midpoint
      case 8: self = .thirdQuartile
      case 9: self = .complete
      case 10: self = .progress
      case 11: self = .mute
      case 12: self = .unmute
      case 13: self = .pause
      case 14: self = .click
      case 15: self = .clickThrough
      case 16: self = .rewind
      case 17: self = .resume
      case 18: self = .error
      case 21: self = .expand
      case 22: self = .collapse
      case 24: self = .close
      case 25: self = .closeLinear
      case 26: self = .skip
      case 27: self = .acceptInvitation
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .creativeView: return try container.encode(1)
      case .start: return try container.encode(2)
      case .breakStart: return try container.encode(3)
      case .breakEnd: return try container.encode(4)
      case .impression: return try container.encode(5)
      case .firstQuartile: return try container.encode(6)
      case .midpoint: return try container.encode(7)
      case .thirdQuartile: return try container.encode(8)
      case .complete: return try container.encode(9)
      case .progress: return try container.encode(10)
      case .mute: return try container.encode(11)
      case .unmute: return try container.encode(12)
      case .pause: return try container.encode(13)
      case .click: return try container.encode(14)
      case .clickThrough: return try container.encode(15)
      case .rewind: return try container.encode(16)
      case .resume: return try container.encode(17)
      case .error: return try container.encode(18)
      case .expand: return try container.encode(21)
      case .collapse: return try container.encode(22)
      case .close: return try container.encode(24)
      case .closeLinear: return try container.encode(25)
      case .skip: return try container.encode(26)
      case .acceptInvitation: return try container.encode(27)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.video.stitcher.v1.Event"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
