// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Metadata for used to register live configs.
public struct LiveConfig: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Output only. The resource name of the live config, in the form of
  /// `projects/{project}/locations/{location}/liveConfigs/{id}`.
  public var name: Swift.String = Swift.String()

  /// Required. Source URI for the live stream manifest.
  public var sourceUri: Swift.String = Swift.String()

  /// The default ad tag associated with this live stream config.
  public var adTagUri: Swift.String = Swift.String()

  /// Additional metadata used to register a live stream with Google Ad Manager
  /// (GAM)
  public var gamLiveConfig: GamLiveConfig? = nil

  /// Output only. State of the live config.
  public var state: LiveConfig.State = LiveConfig.State()

  /// Required. Determines how the ads are tracked.
  public var adTracking: AdTracking = AdTracking()

  /// This must refer to a slate in the same
  /// project. If Google Ad Manager (GAM) is used for ads, this string sets the
  /// value of `slateCreativeId` in
  /// https://developers.google.com/ad-manager/api/reference/v202211/LiveStreamEventService.LiveStreamEvent#slateCreativeId
  public var defaultSlate: Swift.String = Swift.String()

  /// Defines the stitcher behavior in case an ad does not align exactly with
  /// the ad break boundaries. If not specified, the default is `CUT_CURRENT`.
  public var stitchingPolicy: LiveConfig.StitchingPolicy = LiveConfig.StitchingPolicy()

  /// The configuration for prefetching ads.
  public var prefetchConfig: PrefetchConfig? = nil

  /// Options for fetching source manifests and segments.
  public var sourceFetchOptions: FetchOptions? = nil

  /// Initialize a new instance of `LiveConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = LiveConfig().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// State of the live config.
  public enum State: Codable, Equatable, Sendable {
    /// State is not specified.
    case unspecified
    /// Live config is being created.
    case creating
    /// Live config is ready for use.
    case ready
    /// Live config is queued up for deletion.
    case deleting
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .creating: return 1
      case .ready: return 2
      case .deleting: return 3
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .creating: return "CREATING"
      case .ready: return "READY"
      case .deleting: return "DELETING"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "CREATING": self = .creating
      case "READY": self = .ready
      case "DELETING": self = .deleting
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .creating
      case 2: self = .ready
      case 3: self = .deleting
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .creating: return try container.encode(1)
      case .ready: return try container.encode(2)
      case .deleting: return try container.encode(3)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Defines the ad stitching behavior in case the ad duration does not align
  /// exactly with the ad break boundaries. If not specified, the default is
  /// `CUT_CURRENT`.
  public enum StitchingPolicy: Codable, Equatable, Sendable {
    /// Stitching policy is not specified.
    case unspecified
    /// Cuts an ad short and returns to content in the middle of the ad.
    case cutCurrent
    /// Finishes stitching the current ad before returning to content.
    case completeAd
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .cutCurrent: return 1
      case .completeAd: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STITCHING_POLICY_UNSPECIFIED"
      case .cutCurrent: return "CUT_CURRENT"
      case .completeAd: return "COMPLETE_AD"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:StitchingPolicy/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STITCHING_POLICY_UNSPECIFIED": self = .unspecified
      case "CUT_CURRENT": self = .cutCurrent
      case "COMPLETE_AD": self = .completeAd
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:StitchingPolicy/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .cutCurrent
      case 2: self = .completeAd
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .cutCurrent: return try container.encode(1)
      case .completeAd: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.video.stitcher.v1.LiveConfig"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
