// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Configuration for a Media CDN key.
public struct MediaCdnKey: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Input only. 64-byte ed25519 private key for this Media CDN key.
  public var privateKey: Foundation.Data = Foundation.Data()

  /// The keyset name of the Media CDN key.
  public var keyName: Swift.String = Swift.String()

  /// Optional. If set, the URL will be signed using the Media CDN token.
  /// Otherwise, the URL would be signed using the standard Media CDN signature.
  public var tokenConfig: MediaCdnKey.TokenConfig? = nil

  /// Initialize a new instance of `MediaCdnKey`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = MediaCdnKey().with { $0.privateKey = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Configuration for a Media CDN token.
  public struct TokenConfig: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Optional. The query parameter in which to find the token.
    ///
    /// The name must be 1-64 characters long and match
    /// the regular expression `[a-zA-Z]([a-zA-Z0-9_-])*` which means the
    /// first character must be a letter, and all following characters
    /// must be a dash, underscore, letter or digit.
    ///
    /// Defaults to `edge-cache-token`.
    public var queryParameter: Swift.String = Swift.String()

    /// Initialize a new instance of `TokenConfig`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = TokenConfig().with { $0.queryParameter = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.video.stitcher.v1.MediaCdnKey.TokenConfig"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.video.stitcher.v1.MediaCdnKey"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
