// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Metadata for the response of an ad request.
public struct ResponseMetadata: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Error message received when making the ad request.
  public var error: Swift.String = Swift.String()

  /// Headers from the response.
  public var headers: GoogleCloudWKT.Struct? = nil

  /// Status code for the response.
  public var statusCode: Swift.String = Swift.String()

  /// Size in bytes of the response.
  public var sizeBytes: Swift.Int32 = Swift.Int32()

  /// Total time elapsed for the response.
  public var duration: GoogleCloudWKT.Duration? = nil

  /// The body of the response.
  public var body: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

  /// Initialize a new instance of `ResponseMetadata`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ResponseMetadata().with { $0.error = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let error = CodingKeys(stringValue: "error")
    static let headers = CodingKeys(stringValue: "headers")
    static let statusCode = CodingKeys(stringValue: "statusCode")
    static let sizeBytes = CodingKeys(stringValue: "sizeBytes")
    static let duration = CodingKeys(stringValue: "duration")
    static let body = CodingKeys(stringValue: "body")

    static let _knownKeys: Set<Swift.String> = [
      "error",
      "headers",
      "statusCode",
      "sizeBytes",
      "duration",
      "body",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .error) {
      self.error = value
    }
    self.headers = try container.decodeIfPresent(GoogleCloudWKT.Struct.self, forKey: .headers)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .statusCode) {
      self.statusCode = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .sizeBytes) {
      self.sizeBytes = value
    }
    self.duration = try container.decodeIfPresent(GoogleCloudWKT.Duration.self, forKey: .duration)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .body) {
      self.body = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleCloudWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.error, forKey: .error)
    try container.encodeIfPresent(self.headers, forKey: .headers)
    try container.encode(self.statusCode, forKey: .statusCode)
    try container.encode(self.sizeBytes, forKey: .sizeBytes)
    try container.encodeIfPresent(self.duration, forKey: .duration)
    try container.encode(self.body, forKey: .body)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.video.stitcher.v1.ResponseMetadata"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
