// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWkt
import GoogleLongRunning
import GoogleRpc
import GoogleCloudGax

/// Video-On-Demand content stitching API allows you to insert ads
/// into (VoD) video on demand files. You will be able to render custom
/// scrubber bars with highlighted ads, enforce ad policies, allow
/// seamless playback and tracking on native players and monetize
/// content with any standard VMAP compliant ad server.
///
/// @Snippet(path: "VideoStitcherServiceQuickstart")
public final class VideoStitcherServiceClient: Clients.VideoStitcherServiceProtocol, Sendable {
  let inner: any Clients.VideoStitcherServiceStub
  let pollingErrorPolicy: GoogleCloudGax.PollingErrorPolicy
  let pollingBackoffPolicy: GoogleCloudGax.BackoffPolicy

  /// Creates a new `VideoStitcherServiceClient` instance.
  public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
    var inner: any Clients.VideoStitcherServiceStub = try Clients.VideoStitcherServiceTransport(
      options)
    inner = Clients.VideoStitcherServiceRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.VideoStitcherServiceLogging(inner, logger: logger)
    }
    self.inner = inner
    self.pollingErrorPolicy = options.pollingErrorPolicy
    self.pollingBackoffPolicy = options.pollingBackoffPolicy
  }

  /// Creates a new CDN key.
  ///
  /// @Snippet(path: "VideoStitcherService_CreateCdnKey")
  public func createCdnKey(
    request: CreateCdnKeyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.createCdnKey(request: request, options: options)
  }

  /// Creates a new CDN key.
  ///
  /// @Snippet(path: "VideoStitcherService_CreateCdnKey")
  public func createCdnKey(
    withPolling: CreateCdnKeyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<CdnKey> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<CdnKey>.State in
      return try op._extractStatus(CdnKey.self)
    }
    let rawOp = try await self.createCdnKey(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<CdnKey>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Lists all CDN keys in the specified project and location.
  ///
  /// @Snippet(path: "VideoStitcherService_ListCdnKeys")
  public func listCdnKeys(
    request: ListCdnKeysRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudVideoStitcherV1.ListCdnKeysResponse {
    try await self.inner.listCdnKeys(request: request, options: options)
  }

  /// Lists all CDN keys in the specified project and location.
  ///
  /// @Snippet(path: "VideoStitcherService_ListCdnKeys")
  public func listCdnKeys(
    byItem: ListCdnKeysRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<CdnKey, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudVideoStitcherV1.ListCdnKeysResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listCdnKeys(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Returns the specified CDN key.
  ///
  /// @Snippet(path: "VideoStitcherService_GetCdnKey")
  public func getCdnKey(
    request: GetCdnKeyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudVideoStitcherV1.CdnKey {
    try await self.inner.getCdnKey(request: request, options: options)
  }

  /// Deletes the specified CDN key.
  ///
  /// @Snippet(path: "VideoStitcherService_DeleteCdnKey")
  public func deleteCdnKey(
    request: DeleteCdnKeyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.deleteCdnKey(request: request, options: options)
  }

  /// Deletes the specified CDN key.
  ///
  /// @Snippet(path: "VideoStitcherService_DeleteCdnKey")
  public func deleteCdnKey(
    withPolling: DeleteCdnKeyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Swift.Void> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<Swift.Void>.State in
      return try op._extractStatusEmpty()
    }
    let rawOp = try await self.deleteCdnKey(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Swift.Void>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Updates the specified CDN key. Only update fields specified
  /// in the call method body.
  ///
  /// @Snippet(path: "VideoStitcherService_UpdateCdnKey")
  public func updateCdnKey(
    request: UpdateCdnKeyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.updateCdnKey(request: request, options: options)
  }

  /// Updates the specified CDN key. Only update fields specified
  /// in the call method body.
  ///
  /// @Snippet(path: "VideoStitcherService_UpdateCdnKey")
  public func updateCdnKey(
    withPolling: UpdateCdnKeyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<CdnKey> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<CdnKey>.State in
      return try op._extractStatus(CdnKey.self)
    }
    let rawOp = try await self.updateCdnKey(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<CdnKey>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Creates a client side playback VOD session and returns the full
  /// tracking and playback metadata of the session.
  ///
  /// @Snippet(path: "VideoStitcherService_CreateVodSession")
  public func createVodSession(
    request: CreateVodSessionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudVideoStitcherV1.VodSession {
    try await self.inner.createVodSession(request: request, options: options)
  }

  /// Returns the full tracking, playback metadata, and relevant ad-ops
  /// logs for the specified VOD session.
  ///
  /// @Snippet(path: "VideoStitcherService_GetVodSession")
  public func getVodSession(
    request: GetVodSessionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudVideoStitcherV1.VodSession {
    try await self.inner.getVodSession(request: request, options: options)
  }

  /// Returns a list of detailed stitching information of the specified VOD
  /// session.
  ///
  /// @Snippet(path: "VideoStitcherService_ListVodStitchDetails")
  public func listVodStitchDetails(
    request: ListVodStitchDetailsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudVideoStitcherV1.ListVodStitchDetailsResponse {
    try await self.inner.listVodStitchDetails(request: request, options: options)
  }

  /// Returns a list of detailed stitching information of the specified VOD
  /// session.
  ///
  /// @Snippet(path: "VideoStitcherService_ListVodStitchDetails")
  public func listVodStitchDetails(
    byItem: ListVodStitchDetailsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<VodStitchDetail, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudVideoStitcherV1.ListVodStitchDetailsResponse
      in
      var request = byItem
      request.pageToken = token
      return try await self.listVodStitchDetails(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Returns the specified stitching information for the specified VOD session.
  ///
  /// @Snippet(path: "VideoStitcherService_GetVodStitchDetail")
  public func getVodStitchDetail(
    request: GetVodStitchDetailRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudVideoStitcherV1.VodStitchDetail {
    try await self.inner.getVodStitchDetail(request: request, options: options)
  }

  /// Return the list of ad tag details for the specified VOD session.
  ///
  /// @Snippet(path: "VideoStitcherService_ListVodAdTagDetails")
  public func listVodAdTagDetails(
    request: ListVodAdTagDetailsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudVideoStitcherV1.ListVodAdTagDetailsResponse {
    try await self.inner.listVodAdTagDetails(request: request, options: options)
  }

  /// Return the list of ad tag details for the specified VOD session.
  ///
  /// @Snippet(path: "VideoStitcherService_ListVodAdTagDetails")
  public func listVodAdTagDetails(
    byItem: ListVodAdTagDetailsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<VodAdTagDetail, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudVideoStitcherV1.ListVodAdTagDetailsResponse
      in
      var request = byItem
      request.pageToken = token
      return try await self.listVodAdTagDetails(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Returns the specified ad tag detail for the specified VOD session.
  ///
  /// @Snippet(path: "VideoStitcherService_GetVodAdTagDetail")
  public func getVodAdTagDetail(
    request: GetVodAdTagDetailRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudVideoStitcherV1.VodAdTagDetail {
    try await self.inner.getVodAdTagDetail(request: request, options: options)
  }

  /// Return the list of ad tag details for the specified live session.
  ///
  /// @Snippet(path: "VideoStitcherService_ListLiveAdTagDetails")
  public func listLiveAdTagDetails(
    request: ListLiveAdTagDetailsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudVideoStitcherV1.ListLiveAdTagDetailsResponse {
    try await self.inner.listLiveAdTagDetails(request: request, options: options)
  }

  /// Return the list of ad tag details for the specified live session.
  ///
  /// @Snippet(path: "VideoStitcherService_ListLiveAdTagDetails")
  public func listLiveAdTagDetails(
    byItem: ListLiveAdTagDetailsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<LiveAdTagDetail, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudVideoStitcherV1.ListLiveAdTagDetailsResponse
      in
      var request = byItem
      request.pageToken = token
      return try await self.listLiveAdTagDetails(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Returns the specified ad tag detail for the specified live session.
  ///
  /// @Snippet(path: "VideoStitcherService_GetLiveAdTagDetail")
  public func getLiveAdTagDetail(
    request: GetLiveAdTagDetailRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudVideoStitcherV1.LiveAdTagDetail {
    try await self.inner.getLiveAdTagDetail(request: request, options: options)
  }

  /// Creates a slate.
  ///
  /// @Snippet(path: "VideoStitcherService_CreateSlate")
  public func createSlate(
    request: CreateSlateRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.createSlate(request: request, options: options)
  }

  /// Creates a slate.
  ///
  /// @Snippet(path: "VideoStitcherService_CreateSlate")
  public func createSlate(
    withPolling: CreateSlateRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Slate> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleCloudGax._PollableOperationImpl<Slate>.State
      in
      return try op._extractStatus(Slate.self)
    }
    let rawOp = try await self.createSlate(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Slate>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Lists all slates in the specified project and location.
  ///
  /// @Snippet(path: "VideoStitcherService_ListSlates")
  public func listSlates(
    request: ListSlatesRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudVideoStitcherV1.ListSlatesResponse {
    try await self.inner.listSlates(request: request, options: options)
  }

  /// Lists all slates in the specified project and location.
  ///
  /// @Snippet(path: "VideoStitcherService_ListSlates")
  public func listSlates(
    byItem: ListSlatesRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Slate, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudVideoStitcherV1.ListSlatesResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listSlates(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Returns the specified slate.
  ///
  /// @Snippet(path: "VideoStitcherService_GetSlate")
  public func getSlate(
    request: GetSlateRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudVideoStitcherV1.Slate {
    try await self.inner.getSlate(request: request, options: options)
  }

  /// Updates the specified slate.
  ///
  /// @Snippet(path: "VideoStitcherService_UpdateSlate")
  public func updateSlate(
    request: UpdateSlateRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.updateSlate(request: request, options: options)
  }

  /// Updates the specified slate.
  ///
  /// @Snippet(path: "VideoStitcherService_UpdateSlate")
  public func updateSlate(
    withPolling: UpdateSlateRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Slate> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleCloudGax._PollableOperationImpl<Slate>.State
      in
      return try op._extractStatus(Slate.self)
    }
    let rawOp = try await self.updateSlate(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Slate>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Deletes the specified slate.
  ///
  /// @Snippet(path: "VideoStitcherService_DeleteSlate")
  public func deleteSlate(
    request: DeleteSlateRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.deleteSlate(request: request, options: options)
  }

  /// Deletes the specified slate.
  ///
  /// @Snippet(path: "VideoStitcherService_DeleteSlate")
  public func deleteSlate(
    withPolling: DeleteSlateRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Swift.Void> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<Swift.Void>.State in
      return try op._extractStatusEmpty()
    }
    let rawOp = try await self.deleteSlate(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Swift.Void>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Creates a new live session.
  ///
  /// @Snippet(path: "VideoStitcherService_CreateLiveSession")
  public func createLiveSession(
    request: CreateLiveSessionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudVideoStitcherV1.LiveSession {
    try await self.inner.createLiveSession(request: request, options: options)
  }

  /// Returns the details for the specified live session.
  ///
  /// @Snippet(path: "VideoStitcherService_GetLiveSession")
  public func getLiveSession(
    request: GetLiveSessionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudVideoStitcherV1.LiveSession {
    try await self.inner.getLiveSession(request: request, options: options)
  }

  /// Registers the live config with the provided unique ID in
  /// the specified region.
  ///
  /// @Snippet(path: "VideoStitcherService_CreateLiveConfig")
  public func createLiveConfig(
    request: CreateLiveConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.createLiveConfig(request: request, options: options)
  }

  /// Registers the live config with the provided unique ID in
  /// the specified region.
  ///
  /// @Snippet(path: "VideoStitcherService_CreateLiveConfig")
  public func createLiveConfig(
    withPolling: CreateLiveConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<LiveConfig> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<LiveConfig>.State in
      return try op._extractStatus(LiveConfig.self)
    }
    let rawOp = try await self.createLiveConfig(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<LiveConfig>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Lists all live configs managed by the Video Stitcher that
  /// belong to the specified project and region.
  ///
  /// @Snippet(path: "VideoStitcherService_ListLiveConfigs")
  public func listLiveConfigs(
    request: ListLiveConfigsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudVideoStitcherV1.ListLiveConfigsResponse {
    try await self.inner.listLiveConfigs(request: request, options: options)
  }

  /// Lists all live configs managed by the Video Stitcher that
  /// belong to the specified project and region.
  ///
  /// @Snippet(path: "VideoStitcherService_ListLiveConfigs")
  public func listLiveConfigs(
    byItem: ListLiveConfigsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<LiveConfig, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudVideoStitcherV1.ListLiveConfigsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listLiveConfigs(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Returns the specified live config managed by the Video
  /// Stitcher service.
  ///
  /// @Snippet(path: "VideoStitcherService_GetLiveConfig")
  public func getLiveConfig(
    request: GetLiveConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudVideoStitcherV1.LiveConfig {
    try await self.inner.getLiveConfig(request: request, options: options)
  }

  /// Deletes the specified live config.
  ///
  /// @Snippet(path: "VideoStitcherService_DeleteLiveConfig")
  public func deleteLiveConfig(
    request: DeleteLiveConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.deleteLiveConfig(request: request, options: options)
  }

  /// Deletes the specified live config.
  ///
  /// @Snippet(path: "VideoStitcherService_DeleteLiveConfig")
  public func deleteLiveConfig(
    withPolling: DeleteLiveConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Swift.Void> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<Swift.Void>.State in
      return try op._extractStatusEmpty()
    }
    let rawOp = try await self.deleteLiveConfig(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Swift.Void>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Updates the specified LiveConfig. Only update fields specified
  /// in the call method body.
  ///
  /// @Snippet(path: "VideoStitcherService_UpdateLiveConfig")
  public func updateLiveConfig(
    request: UpdateLiveConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.updateLiveConfig(request: request, options: options)
  }

  /// Updates the specified LiveConfig. Only update fields specified
  /// in the call method body.
  ///
  /// @Snippet(path: "VideoStitcherService_UpdateLiveConfig")
  public func updateLiveConfig(
    withPolling: UpdateLiveConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<LiveConfig> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<LiveConfig>.State in
      return try op._extractStatus(LiveConfig.self)
    }
    let rawOp = try await self.updateLiveConfig(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<LiveConfig>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Registers the VOD config with the provided unique ID in
  /// the specified region.
  ///
  /// @Snippet(path: "VideoStitcherService_CreateVodConfig")
  public func createVodConfig(
    request: CreateVodConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.createVodConfig(request: request, options: options)
  }

  /// Registers the VOD config with the provided unique ID in
  /// the specified region.
  ///
  /// @Snippet(path: "VideoStitcherService_CreateVodConfig")
  public func createVodConfig(
    withPolling: CreateVodConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<VodConfig> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<VodConfig>.State in
      return try op._extractStatus(VodConfig.self)
    }
    let rawOp = try await self.createVodConfig(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<VodConfig>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Lists all VOD configs managed by the Video Stitcher API that
  /// belong to the specified project and region.
  ///
  /// @Snippet(path: "VideoStitcherService_ListVodConfigs")
  public func listVodConfigs(
    request: ListVodConfigsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudVideoStitcherV1.ListVodConfigsResponse {
    try await self.inner.listVodConfigs(request: request, options: options)
  }

  /// Lists all VOD configs managed by the Video Stitcher API that
  /// belong to the specified project and region.
  ///
  /// @Snippet(path: "VideoStitcherService_ListVodConfigs")
  public func listVodConfigs(
    byItem: ListVodConfigsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<VodConfig, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudVideoStitcherV1.ListVodConfigsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listVodConfigs(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Returns the specified VOD config managed by the Video
  /// Stitcher API service.
  ///
  /// @Snippet(path: "VideoStitcherService_GetVodConfig")
  public func getVodConfig(
    request: GetVodConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudVideoStitcherV1.VodConfig {
    try await self.inner.getVodConfig(request: request, options: options)
  }

  /// Deletes the specified VOD config.
  ///
  /// @Snippet(path: "VideoStitcherService_DeleteVodConfig")
  public func deleteVodConfig(
    request: DeleteVodConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.deleteVodConfig(request: request, options: options)
  }

  /// Deletes the specified VOD config.
  ///
  /// @Snippet(path: "VideoStitcherService_DeleteVodConfig")
  public func deleteVodConfig(
    withPolling: DeleteVodConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Swift.Void> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<Swift.Void>.State in
      return try op._extractStatusEmpty()
    }
    let rawOp = try await self.deleteVodConfig(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Swift.Void>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Updates the specified VOD config. Only update fields specified
  /// in the call method body.
  ///
  /// @Snippet(path: "VideoStitcherService_UpdateVodConfig")
  public func updateVodConfig(
    request: UpdateVodConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.updateVodConfig(request: request, options: options)
  }

  /// Updates the specified VOD config. Only update fields specified
  /// in the call method body.
  ///
  /// @Snippet(path: "VideoStitcherService_UpdateVodConfig")
  public func updateVodConfig(
    withPolling: UpdateVodConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<VodConfig> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<VodConfig>.State in
      return try op._extractStatus(VodConfig.self)
    }
    let rawOp = try await self.updateVodConfig(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<VodConfig>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "VideoStitcherService_ListOperations")
  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    try await self.inner.listOperations(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "VideoStitcherService_ListOperations")
  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listOperations(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "VideoStitcherService_GetOperation")
  func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.getOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "VideoStitcherService_DeleteOperation")
  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    try await self.inner.deleteOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "VideoStitcherService_CancelOperation")
  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    try await self.inner.cancelOperation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `VideoStitcherServiceClient`.
  ///
  /// To mock `VideoStitcherServiceClient` change your functions to receive
  /// `some VideoStitcherServiceProtocol` or `any VideoStitcherServiceProtocol`
  /// and pass a mock implementation in your tests.
  public protocol VideoStitcherServiceProtocol {
    /// See `VideoStitcherServiceClient.createCdnKey`.
    func createCdnKey(request: CreateCdnKeyRequest) async throws -> GoogleLongRunning.Operation

    /// See `VideoStitcherServiceClient.createCdnKey`.
    func createCdnKey(withPolling: CreateCdnKeyRequest) async throws -> any GoogleCloudGax
      .PollableOperation<CdnKey>

    /// See `VideoStitcherServiceClient.createCdnKey`.
    func createCdnKey(
      parent: Swift.String,
      cdnKey: CdnKey?,
      cdnKeyId: Swift.String,
    ) async throws -> any GoogleCloudGax.PollableOperation<CdnKey>

    /// See `VideoStitcherServiceClient.listCdnKeys`.
    func listCdnKeys(request: ListCdnKeysRequest) async throws
      -> GoogleCloudVideoStitcherV1.ListCdnKeysResponse

    /// See `VideoStitcherServiceClient.listCdnKeys`.
    func listCdnKeys(
      byItem: ListCdnKeysRequest
    ) throws -> any AsyncSequence<CdnKey, Swift.Error>

    /// See `VideoStitcherServiceClient.listCdnKeys`.
    func listCdnKeys(
      parent: Swift.String,
    ) throws -> any AsyncSequence<CdnKey, Swift.Error>

    /// See `VideoStitcherServiceClient.getCdnKey`.
    func getCdnKey(request: GetCdnKeyRequest) async throws -> GoogleCloudVideoStitcherV1.CdnKey

    /// See `VideoStitcherServiceClient.getCdnKey`.
    func getCdnKey(
      name: Swift.String,
    ) async throws -> GoogleCloudVideoStitcherV1.CdnKey

    /// See `VideoStitcherServiceClient.deleteCdnKey`.
    func deleteCdnKey(request: DeleteCdnKeyRequest) async throws -> GoogleLongRunning.Operation

    /// See `VideoStitcherServiceClient.deleteCdnKey`.
    func deleteCdnKey(withPolling: DeleteCdnKeyRequest) async throws -> any GoogleCloudGax
      .PollableOperation<Swift.Void>

    /// See `VideoStitcherServiceClient.deleteCdnKey`.
    func deleteCdnKey(
      name: Swift.String,
    ) async throws -> any GoogleCloudGax.PollableOperation<Swift.Void>

    /// See `VideoStitcherServiceClient.updateCdnKey`.
    func updateCdnKey(request: UpdateCdnKeyRequest) async throws -> GoogleLongRunning.Operation

    /// See `VideoStitcherServiceClient.updateCdnKey`.
    func updateCdnKey(withPolling: UpdateCdnKeyRequest) async throws -> any GoogleCloudGax
      .PollableOperation<CdnKey>

    /// See `VideoStitcherServiceClient.updateCdnKey`.
    func updateCdnKey(
      cdnKey: CdnKey?,
      updateMask: GoogleCloudWkt.FieldMask?,
    ) async throws -> any GoogleCloudGax.PollableOperation<CdnKey>

    /// See `VideoStitcherServiceClient.createVodSession`.
    func createVodSession(request: CreateVodSessionRequest) async throws
      -> GoogleCloudVideoStitcherV1.VodSession

    /// See `VideoStitcherServiceClient.createVodSession`.
    func createVodSession(
      parent: Swift.String,
      vodSession: VodSession?,
    ) async throws -> GoogleCloudVideoStitcherV1.VodSession

    /// See `VideoStitcherServiceClient.getVodSession`.
    func getVodSession(request: GetVodSessionRequest) async throws
      -> GoogleCloudVideoStitcherV1.VodSession

    /// See `VideoStitcherServiceClient.getVodSession`.
    func getVodSession(
      name: Swift.String,
    ) async throws -> GoogleCloudVideoStitcherV1.VodSession

    /// See `VideoStitcherServiceClient.listVodStitchDetails`.
    func listVodStitchDetails(request: ListVodStitchDetailsRequest) async throws
      -> GoogleCloudVideoStitcherV1.ListVodStitchDetailsResponse

    /// See `VideoStitcherServiceClient.listVodStitchDetails`.
    func listVodStitchDetails(
      byItem: ListVodStitchDetailsRequest
    ) throws -> any AsyncSequence<VodStitchDetail, Swift.Error>

    /// See `VideoStitcherServiceClient.listVodStitchDetails`.
    func listVodStitchDetails(
      parent: Swift.String,
    ) throws -> any AsyncSequence<VodStitchDetail, Swift.Error>

    /// See `VideoStitcherServiceClient.getVodStitchDetail`.
    func getVodStitchDetail(request: GetVodStitchDetailRequest) async throws
      -> GoogleCloudVideoStitcherV1.VodStitchDetail

    /// See `VideoStitcherServiceClient.getVodStitchDetail`.
    func getVodStitchDetail(
      name: Swift.String,
    ) async throws -> GoogleCloudVideoStitcherV1.VodStitchDetail

    /// See `VideoStitcherServiceClient.listVodAdTagDetails`.
    func listVodAdTagDetails(request: ListVodAdTagDetailsRequest) async throws
      -> GoogleCloudVideoStitcherV1.ListVodAdTagDetailsResponse

    /// See `VideoStitcherServiceClient.listVodAdTagDetails`.
    func listVodAdTagDetails(
      byItem: ListVodAdTagDetailsRequest
    ) throws -> any AsyncSequence<VodAdTagDetail, Swift.Error>

    /// See `VideoStitcherServiceClient.listVodAdTagDetails`.
    func listVodAdTagDetails(
      parent: Swift.String,
    ) throws -> any AsyncSequence<VodAdTagDetail, Swift.Error>

    /// See `VideoStitcherServiceClient.getVodAdTagDetail`.
    func getVodAdTagDetail(request: GetVodAdTagDetailRequest) async throws
      -> GoogleCloudVideoStitcherV1.VodAdTagDetail

    /// See `VideoStitcherServiceClient.getVodAdTagDetail`.
    func getVodAdTagDetail(
      name: Swift.String,
    ) async throws -> GoogleCloudVideoStitcherV1.VodAdTagDetail

    /// See `VideoStitcherServiceClient.listLiveAdTagDetails`.
    func listLiveAdTagDetails(request: ListLiveAdTagDetailsRequest) async throws
      -> GoogleCloudVideoStitcherV1.ListLiveAdTagDetailsResponse

    /// See `VideoStitcherServiceClient.listLiveAdTagDetails`.
    func listLiveAdTagDetails(
      byItem: ListLiveAdTagDetailsRequest
    ) throws -> any AsyncSequence<LiveAdTagDetail, Swift.Error>

    /// See `VideoStitcherServiceClient.listLiveAdTagDetails`.
    func listLiveAdTagDetails(
      parent: Swift.String,
    ) throws -> any AsyncSequence<LiveAdTagDetail, Swift.Error>

    /// See `VideoStitcherServiceClient.getLiveAdTagDetail`.
    func getLiveAdTagDetail(request: GetLiveAdTagDetailRequest) async throws
      -> GoogleCloudVideoStitcherV1.LiveAdTagDetail

    /// See `VideoStitcherServiceClient.getLiveAdTagDetail`.
    func getLiveAdTagDetail(
      name: Swift.String,
    ) async throws -> GoogleCloudVideoStitcherV1.LiveAdTagDetail

    /// See `VideoStitcherServiceClient.createSlate`.
    func createSlate(request: CreateSlateRequest) async throws -> GoogleLongRunning.Operation

    /// See `VideoStitcherServiceClient.createSlate`.
    func createSlate(withPolling: CreateSlateRequest) async throws -> any GoogleCloudGax
      .PollableOperation<Slate>

    /// See `VideoStitcherServiceClient.createSlate`.
    func createSlate(
      parent: Swift.String,
      slate: Slate?,
      slateId: Swift.String,
    ) async throws -> any GoogleCloudGax.PollableOperation<Slate>

    /// See `VideoStitcherServiceClient.listSlates`.
    func listSlates(request: ListSlatesRequest) async throws
      -> GoogleCloudVideoStitcherV1.ListSlatesResponse

    /// See `VideoStitcherServiceClient.listSlates`.
    func listSlates(
      byItem: ListSlatesRequest
    ) throws -> any AsyncSequence<Slate, Swift.Error>

    /// See `VideoStitcherServiceClient.listSlates`.
    func listSlates(
      parent: Swift.String,
    ) throws -> any AsyncSequence<Slate, Swift.Error>

    /// See `VideoStitcherServiceClient.getSlate`.
    func getSlate(request: GetSlateRequest) async throws -> GoogleCloudVideoStitcherV1.Slate

    /// See `VideoStitcherServiceClient.getSlate`.
    func getSlate(
      name: Swift.String,
    ) async throws -> GoogleCloudVideoStitcherV1.Slate

    /// See `VideoStitcherServiceClient.updateSlate`.
    func updateSlate(request: UpdateSlateRequest) async throws -> GoogleLongRunning.Operation

    /// See `VideoStitcherServiceClient.updateSlate`.
    func updateSlate(withPolling: UpdateSlateRequest) async throws -> any GoogleCloudGax
      .PollableOperation<Slate>

    /// See `VideoStitcherServiceClient.updateSlate`.
    func updateSlate(
      slate: Slate?,
      updateMask: GoogleCloudWkt.FieldMask?,
    ) async throws -> any GoogleCloudGax.PollableOperation<Slate>

    /// See `VideoStitcherServiceClient.deleteSlate`.
    func deleteSlate(request: DeleteSlateRequest) async throws -> GoogleLongRunning.Operation

    /// See `VideoStitcherServiceClient.deleteSlate`.
    func deleteSlate(withPolling: DeleteSlateRequest) async throws -> any GoogleCloudGax
      .PollableOperation<Swift.Void>

    /// See `VideoStitcherServiceClient.deleteSlate`.
    func deleteSlate(
      name: Swift.String,
    ) async throws -> any GoogleCloudGax.PollableOperation<Swift.Void>

    /// See `VideoStitcherServiceClient.createLiveSession`.
    func createLiveSession(request: CreateLiveSessionRequest) async throws
      -> GoogleCloudVideoStitcherV1.LiveSession

    /// See `VideoStitcherServiceClient.createLiveSession`.
    func createLiveSession(
      parent: Swift.String,
      liveSession: LiveSession?,
    ) async throws -> GoogleCloudVideoStitcherV1.LiveSession

    /// See `VideoStitcherServiceClient.getLiveSession`.
    func getLiveSession(request: GetLiveSessionRequest) async throws
      -> GoogleCloudVideoStitcherV1.LiveSession

    /// See `VideoStitcherServiceClient.getLiveSession`.
    func getLiveSession(
      name: Swift.String,
    ) async throws -> GoogleCloudVideoStitcherV1.LiveSession

    /// See `VideoStitcherServiceClient.createLiveConfig`.
    func createLiveConfig(request: CreateLiveConfigRequest) async throws
      -> GoogleLongRunning.Operation

    /// See `VideoStitcherServiceClient.createLiveConfig`.
    func createLiveConfig(withPolling: CreateLiveConfigRequest) async throws -> any GoogleCloudGax
      .PollableOperation<LiveConfig>

    /// See `VideoStitcherServiceClient.createLiveConfig`.
    func createLiveConfig(
      parent: Swift.String,
      liveConfig: LiveConfig?,
      liveConfigId: Swift.String,
    ) async throws -> any GoogleCloudGax.PollableOperation<LiveConfig>

    /// See `VideoStitcherServiceClient.listLiveConfigs`.
    func listLiveConfigs(request: ListLiveConfigsRequest) async throws
      -> GoogleCloudVideoStitcherV1.ListLiveConfigsResponse

    /// See `VideoStitcherServiceClient.listLiveConfigs`.
    func listLiveConfigs(
      byItem: ListLiveConfigsRequest
    ) throws -> any AsyncSequence<LiveConfig, Swift.Error>

    /// See `VideoStitcherServiceClient.listLiveConfigs`.
    func listLiveConfigs(
      parent: Swift.String,
    ) throws -> any AsyncSequence<LiveConfig, Swift.Error>

    /// See `VideoStitcherServiceClient.getLiveConfig`.
    func getLiveConfig(request: GetLiveConfigRequest) async throws
      -> GoogleCloudVideoStitcherV1.LiveConfig

    /// See `VideoStitcherServiceClient.getLiveConfig`.
    func getLiveConfig(
      name: Swift.String,
    ) async throws -> GoogleCloudVideoStitcherV1.LiveConfig

    /// See `VideoStitcherServiceClient.deleteLiveConfig`.
    func deleteLiveConfig(request: DeleteLiveConfigRequest) async throws
      -> GoogleLongRunning.Operation

    /// See `VideoStitcherServiceClient.deleteLiveConfig`.
    func deleteLiveConfig(withPolling: DeleteLiveConfigRequest) async throws -> any GoogleCloudGax
      .PollableOperation<Swift.Void>

    /// See `VideoStitcherServiceClient.deleteLiveConfig`.
    func deleteLiveConfig(
      name: Swift.String,
    ) async throws -> any GoogleCloudGax.PollableOperation<Swift.Void>

    /// See `VideoStitcherServiceClient.updateLiveConfig`.
    func updateLiveConfig(request: UpdateLiveConfigRequest) async throws
      -> GoogleLongRunning.Operation

    /// See `VideoStitcherServiceClient.updateLiveConfig`.
    func updateLiveConfig(withPolling: UpdateLiveConfigRequest) async throws -> any GoogleCloudGax
      .PollableOperation<LiveConfig>

    /// See `VideoStitcherServiceClient.updateLiveConfig`.
    func updateLiveConfig(
      liveConfig: LiveConfig?,
      updateMask: GoogleCloudWkt.FieldMask?,
    ) async throws -> any GoogleCloudGax.PollableOperation<LiveConfig>

    /// See `VideoStitcherServiceClient.createVodConfig`.
    func createVodConfig(request: CreateVodConfigRequest) async throws
      -> GoogleLongRunning.Operation

    /// See `VideoStitcherServiceClient.createVodConfig`.
    func createVodConfig(withPolling: CreateVodConfigRequest) async throws -> any GoogleCloudGax
      .PollableOperation<VodConfig>

    /// See `VideoStitcherServiceClient.createVodConfig`.
    func createVodConfig(
      parent: Swift.String,
      vodConfig: VodConfig?,
      vodConfigId: Swift.String,
    ) async throws -> any GoogleCloudGax.PollableOperation<VodConfig>

    /// See `VideoStitcherServiceClient.listVodConfigs`.
    func listVodConfigs(request: ListVodConfigsRequest) async throws
      -> GoogleCloudVideoStitcherV1.ListVodConfigsResponse

    /// See `VideoStitcherServiceClient.listVodConfigs`.
    func listVodConfigs(
      byItem: ListVodConfigsRequest
    ) throws -> any AsyncSequence<VodConfig, Swift.Error>

    /// See `VideoStitcherServiceClient.listVodConfigs`.
    func listVodConfigs(
      parent: Swift.String,
    ) throws -> any AsyncSequence<VodConfig, Swift.Error>

    /// See `VideoStitcherServiceClient.getVodConfig`.
    func getVodConfig(request: GetVodConfigRequest) async throws
      -> GoogleCloudVideoStitcherV1.VodConfig

    /// See `VideoStitcherServiceClient.getVodConfig`.
    func getVodConfig(
      name: Swift.String,
    ) async throws -> GoogleCloudVideoStitcherV1.VodConfig

    /// See `VideoStitcherServiceClient.deleteVodConfig`.
    func deleteVodConfig(request: DeleteVodConfigRequest) async throws
      -> GoogleLongRunning.Operation

    /// See `VideoStitcherServiceClient.deleteVodConfig`.
    func deleteVodConfig(withPolling: DeleteVodConfigRequest) async throws -> any GoogleCloudGax
      .PollableOperation<Swift.Void>

    /// See `VideoStitcherServiceClient.deleteVodConfig`.
    func deleteVodConfig(
      name: Swift.String,
    ) async throws -> any GoogleCloudGax.PollableOperation<Swift.Void>

    /// See `VideoStitcherServiceClient.updateVodConfig`.
    func updateVodConfig(request: UpdateVodConfigRequest) async throws
      -> GoogleLongRunning.Operation

    /// See `VideoStitcherServiceClient.updateVodConfig`.
    func updateVodConfig(withPolling: UpdateVodConfigRequest) async throws -> any GoogleCloudGax
      .PollableOperation<VodConfig>

    /// See `VideoStitcherServiceClient.updateVodConfig`.
    func updateVodConfig(
      vodConfig: VodConfig?,
      updateMask: GoogleCloudWkt.FieldMask?,
    ) async throws -> any GoogleCloudGax.PollableOperation<VodConfig>

    /// See `VideoStitcherServiceClient.listOperations`.
    func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
      -> GoogleLongRunning.ListOperationsResponse

    /// See `VideoStitcherServiceClient.listOperations`.
    func listOperations(
      byItem: GoogleLongRunning.ListOperationsRequest
    ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>

    /// See `VideoStitcherServiceClient.listOperations`.
    func listOperations(
      name: Swift.String,
      filter: Swift.String,
    ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>

    /// See `VideoStitcherServiceClient.deleteOperation`.
    func deleteOperation(request: GoogleLongRunning.DeleteOperationRequest) async throws

    /// See `VideoStitcherServiceClient.deleteOperation`.
    func deleteOperation(
      name: Swift.String,
    ) async throws

    /// See `VideoStitcherServiceClient.cancelOperation`.
    func cancelOperation(request: GoogleLongRunning.CancelOperationRequest) async throws

    /// See `VideoStitcherServiceClient.cancelOperation`.
    func cancelOperation(
      name: Swift.String,
    ) async throws

    /// See `VideoStitcherServiceClient.createCdnKey`.
    func createCdnKey(
      request: CreateCdnKeyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `VideoStitcherServiceClient.createCdnKey`.
    func createCdnKey(
      withPolling: CreateCdnKeyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<CdnKey>

    /// See `VideoStitcherServiceClient.listCdnKeys`.
    func listCdnKeys(
      request: ListCdnKeysRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudVideoStitcherV1.ListCdnKeysResponse

    /// See `VideoStitcherServiceClient.listCdnKeys`.
    func listCdnKeys(
      byItem: ListCdnKeysRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<CdnKey, Swift.Error>

    /// See `VideoStitcherServiceClient.getCdnKey`.
    func getCdnKey(
      request: GetCdnKeyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudVideoStitcherV1.CdnKey

    /// See `VideoStitcherServiceClient.deleteCdnKey`.
    func deleteCdnKey(
      request: DeleteCdnKeyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `VideoStitcherServiceClient.deleteCdnKey`.
    func deleteCdnKey(
      withPolling: DeleteCdnKeyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Swift.Void>

    /// See `VideoStitcherServiceClient.updateCdnKey`.
    func updateCdnKey(
      request: UpdateCdnKeyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `VideoStitcherServiceClient.updateCdnKey`.
    func updateCdnKey(
      withPolling: UpdateCdnKeyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<CdnKey>

    /// See `VideoStitcherServiceClient.createVodSession`.
    func createVodSession(
      request: CreateVodSessionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudVideoStitcherV1.VodSession

    /// See `VideoStitcherServiceClient.getVodSession`.
    func getVodSession(
      request: GetVodSessionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudVideoStitcherV1.VodSession

    /// See `VideoStitcherServiceClient.listVodStitchDetails`.
    func listVodStitchDetails(
      request: ListVodStitchDetailsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudVideoStitcherV1.ListVodStitchDetailsResponse

    /// See `VideoStitcherServiceClient.listVodStitchDetails`.
    func listVodStitchDetails(
      byItem: ListVodStitchDetailsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<VodStitchDetail, Swift.Error>

    /// See `VideoStitcherServiceClient.getVodStitchDetail`.
    func getVodStitchDetail(
      request: GetVodStitchDetailRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudVideoStitcherV1.VodStitchDetail

    /// See `VideoStitcherServiceClient.listVodAdTagDetails`.
    func listVodAdTagDetails(
      request: ListVodAdTagDetailsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudVideoStitcherV1.ListVodAdTagDetailsResponse

    /// See `VideoStitcherServiceClient.listVodAdTagDetails`.
    func listVodAdTagDetails(
      byItem: ListVodAdTagDetailsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<VodAdTagDetail, Swift.Error>

    /// See `VideoStitcherServiceClient.getVodAdTagDetail`.
    func getVodAdTagDetail(
      request: GetVodAdTagDetailRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudVideoStitcherV1.VodAdTagDetail

    /// See `VideoStitcherServiceClient.listLiveAdTagDetails`.
    func listLiveAdTagDetails(
      request: ListLiveAdTagDetailsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudVideoStitcherV1.ListLiveAdTagDetailsResponse

    /// See `VideoStitcherServiceClient.listLiveAdTagDetails`.
    func listLiveAdTagDetails(
      byItem: ListLiveAdTagDetailsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<LiveAdTagDetail, Swift.Error>

    /// See `VideoStitcherServiceClient.getLiveAdTagDetail`.
    func getLiveAdTagDetail(
      request: GetLiveAdTagDetailRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudVideoStitcherV1.LiveAdTagDetail

    /// See `VideoStitcherServiceClient.createSlate`.
    func createSlate(
      request: CreateSlateRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `VideoStitcherServiceClient.createSlate`.
    func createSlate(
      withPolling: CreateSlateRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Slate>

    /// See `VideoStitcherServiceClient.listSlates`.
    func listSlates(
      request: ListSlatesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudVideoStitcherV1.ListSlatesResponse

    /// See `VideoStitcherServiceClient.listSlates`.
    func listSlates(
      byItem: ListSlatesRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<Slate, Swift.Error>

    /// See `VideoStitcherServiceClient.getSlate`.
    func getSlate(
      request: GetSlateRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudVideoStitcherV1.Slate

    /// See `VideoStitcherServiceClient.updateSlate`.
    func updateSlate(
      request: UpdateSlateRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `VideoStitcherServiceClient.updateSlate`.
    func updateSlate(
      withPolling: UpdateSlateRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Slate>

    /// See `VideoStitcherServiceClient.deleteSlate`.
    func deleteSlate(
      request: DeleteSlateRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `VideoStitcherServiceClient.deleteSlate`.
    func deleteSlate(
      withPolling: DeleteSlateRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Swift.Void>

    /// See `VideoStitcherServiceClient.createLiveSession`.
    func createLiveSession(
      request: CreateLiveSessionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudVideoStitcherV1.LiveSession

    /// See `VideoStitcherServiceClient.getLiveSession`.
    func getLiveSession(
      request: GetLiveSessionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudVideoStitcherV1.LiveSession

    /// See `VideoStitcherServiceClient.createLiveConfig`.
    func createLiveConfig(
      request: CreateLiveConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `VideoStitcherServiceClient.createLiveConfig`.
    func createLiveConfig(
      withPolling: CreateLiveConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<LiveConfig>

    /// See `VideoStitcherServiceClient.listLiveConfigs`.
    func listLiveConfigs(
      request: ListLiveConfigsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudVideoStitcherV1.ListLiveConfigsResponse

    /// See `VideoStitcherServiceClient.listLiveConfigs`.
    func listLiveConfigs(
      byItem: ListLiveConfigsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<LiveConfig, Swift.Error>

    /// See `VideoStitcherServiceClient.getLiveConfig`.
    func getLiveConfig(
      request: GetLiveConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudVideoStitcherV1.LiveConfig

    /// See `VideoStitcherServiceClient.deleteLiveConfig`.
    func deleteLiveConfig(
      request: DeleteLiveConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `VideoStitcherServiceClient.deleteLiveConfig`.
    func deleteLiveConfig(
      withPolling: DeleteLiveConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Swift.Void>

    /// See `VideoStitcherServiceClient.updateLiveConfig`.
    func updateLiveConfig(
      request: UpdateLiveConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `VideoStitcherServiceClient.updateLiveConfig`.
    func updateLiveConfig(
      withPolling: UpdateLiveConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<LiveConfig>

    /// See `VideoStitcherServiceClient.createVodConfig`.
    func createVodConfig(
      request: CreateVodConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `VideoStitcherServiceClient.createVodConfig`.
    func createVodConfig(
      withPolling: CreateVodConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<VodConfig>

    /// See `VideoStitcherServiceClient.listVodConfigs`.
    func listVodConfigs(
      request: ListVodConfigsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudVideoStitcherV1.ListVodConfigsResponse

    /// See `VideoStitcherServiceClient.listVodConfigs`.
    func listVodConfigs(
      byItem: ListVodConfigsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<VodConfig, Swift.Error>

    /// See `VideoStitcherServiceClient.getVodConfig`.
    func getVodConfig(
      request: GetVodConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudVideoStitcherV1.VodConfig

    /// See `VideoStitcherServiceClient.deleteVodConfig`.
    func deleteVodConfig(
      request: DeleteVodConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `VideoStitcherServiceClient.deleteVodConfig`.
    func deleteVodConfig(
      withPolling: DeleteVodConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Swift.Void>

    /// See `VideoStitcherServiceClient.updateVodConfig`.
    func updateVodConfig(
      request: UpdateVodConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `VideoStitcherServiceClient.updateVodConfig`.
    func updateVodConfig(
      withPolling: UpdateVodConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<VodConfig>

    /// See `VideoStitcherServiceClient.listOperations`.
    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse

    /// See `VideoStitcherServiceClient.listOperations`.
    func listOperations(
      byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>

    /// See `VideoStitcherServiceClient.deleteOperation`.
    func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    /// See `VideoStitcherServiceClient.cancelOperation`.
    func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws
  }
}

// Default implementations
extension Clients.VideoStitcherServiceProtocol {
  public func createCdnKey(request: CreateCdnKeyRequest) async throws -> GoogleLongRunning.Operation
  {
    try await self.createCdnKey(request: request, options: .init())
  }

  public func createCdnKey(
    request: CreateCdnKeyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func createCdnKey(withPolling: CreateCdnKeyRequest) async throws -> any GoogleCloudGax
    .PollableOperation<CdnKey>
  {
    try await self.createCdnKey(withPolling: withPolling, options: .init())
  }

  public func createCdnKey(
    withPolling: CreateCdnKeyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<CdnKey> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<CdnKey>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func createCdnKey(
    parent: Swift.String,
    cdnKey: CdnKey?,
    cdnKeyId: Swift.String,
  ) async throws -> any GoogleCloudGax.PollableOperation<CdnKey> {
    let request = CreateCdnKeyRequest().with {
      $0.parent = parent
      $0.cdnKey = cdnKey
      $0.cdnKeyId = cdnKeyId
    }
    return try await self.createCdnKey(withPolling: request)
  }

  public func listCdnKeys(request: ListCdnKeysRequest) async throws
    -> GoogleCloudVideoStitcherV1.ListCdnKeysResponse
  {
    try await self.listCdnKeys(request: request, options: .init())
  }

  public func listCdnKeys(
    request: ListCdnKeysRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudVideoStitcherV1.ListCdnKeysResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listCdnKeys(
    byItem: ListCdnKeysRequest
  ) throws -> any AsyncSequence<CdnKey, Swift.Error> {
    try self.listCdnKeys(byItem: byItem, options: .init())
  }

  public func listCdnKeys(
    byItem: ListCdnKeysRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<CdnKey, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudVideoStitcherV1.ListCdnKeysResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listCdnKeys(
    parent: Swift.String,
  ) throws -> any AsyncSequence<CdnKey, Swift.Error> {
    let request = ListCdnKeysRequest().with {
      $0.parent = parent
    }
    return try self.listCdnKeys(byItem: request)
  }

  public func getCdnKey(request: GetCdnKeyRequest) async throws -> GoogleCloudVideoStitcherV1.CdnKey
  {
    try await self.getCdnKey(request: request, options: .init())
  }

  public func getCdnKey(
    request: GetCdnKeyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudVideoStitcherV1.CdnKey {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getCdnKey(
    name: Swift.String,
  ) async throws -> GoogleCloudVideoStitcherV1.CdnKey {
    let request = GetCdnKeyRequest().with {
      $0.name = name
    }
    return try await self.getCdnKey(request: request)
  }

  public func deleteCdnKey(request: DeleteCdnKeyRequest) async throws -> GoogleLongRunning.Operation
  {
    try await self.deleteCdnKey(request: request, options: .init())
  }

  public func deleteCdnKey(
    request: DeleteCdnKeyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteCdnKey(withPolling: DeleteCdnKeyRequest) async throws -> any GoogleCloudGax
    .PollableOperation<Swift.Void>
  {
    try await self.deleteCdnKey(withPolling: withPolling, options: .init())
  }

  public func deleteCdnKey(
    withPolling: DeleteCdnKeyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Swift.Void> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Swift.Void>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func deleteCdnKey(
    name: Swift.String,
  ) async throws -> any GoogleCloudGax.PollableOperation<Swift.Void> {
    let request = DeleteCdnKeyRequest().with {
      $0.name = name
    }
    return try await self.deleteCdnKey(withPolling: request)
  }

  public func updateCdnKey(request: UpdateCdnKeyRequest) async throws -> GoogleLongRunning.Operation
  {
    try await self.updateCdnKey(request: request, options: .init())
  }

  public func updateCdnKey(
    request: UpdateCdnKeyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func updateCdnKey(withPolling: UpdateCdnKeyRequest) async throws -> any GoogleCloudGax
    .PollableOperation<CdnKey>
  {
    try await self.updateCdnKey(withPolling: withPolling, options: .init())
  }

  public func updateCdnKey(
    withPolling: UpdateCdnKeyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<CdnKey> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<CdnKey>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func updateCdnKey(
    cdnKey: CdnKey?,
    updateMask: GoogleCloudWkt.FieldMask?,
  ) async throws -> any GoogleCloudGax.PollableOperation<CdnKey> {
    let request = UpdateCdnKeyRequest().with {
      $0.cdnKey = cdnKey
      $0.updateMask = updateMask
    }
    return try await self.updateCdnKey(withPolling: request)
  }

  public func createVodSession(request: CreateVodSessionRequest) async throws
    -> GoogleCloudVideoStitcherV1.VodSession
  {
    try await self.createVodSession(request: request, options: .init())
  }

  public func createVodSession(
    request: CreateVodSessionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudVideoStitcherV1.VodSession {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func createVodSession(
    parent: Swift.String,
    vodSession: VodSession?,
  ) async throws -> GoogleCloudVideoStitcherV1.VodSession {
    let request = CreateVodSessionRequest().with {
      $0.parent = parent
      $0.vodSession = vodSession
    }
    return try await self.createVodSession(request: request)
  }

  public func getVodSession(request: GetVodSessionRequest) async throws
    -> GoogleCloudVideoStitcherV1.VodSession
  {
    try await self.getVodSession(request: request, options: .init())
  }

  public func getVodSession(
    request: GetVodSessionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudVideoStitcherV1.VodSession {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getVodSession(
    name: Swift.String,
  ) async throws -> GoogleCloudVideoStitcherV1.VodSession {
    let request = GetVodSessionRequest().with {
      $0.name = name
    }
    return try await self.getVodSession(request: request)
  }

  public func listVodStitchDetails(request: ListVodStitchDetailsRequest) async throws
    -> GoogleCloudVideoStitcherV1.ListVodStitchDetailsResponse
  {
    try await self.listVodStitchDetails(request: request, options: .init())
  }

  public func listVodStitchDetails(
    request: ListVodStitchDetailsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudVideoStitcherV1.ListVodStitchDetailsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listVodStitchDetails(
    byItem: ListVodStitchDetailsRequest
  ) throws -> any AsyncSequence<VodStitchDetail, Swift.Error> {
    try self.listVodStitchDetails(byItem: byItem, options: .init())
  }

  public func listVodStitchDetails(
    byItem: ListVodStitchDetailsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<VodStitchDetail, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudVideoStitcherV1.ListVodStitchDetailsResponse
      in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listVodStitchDetails(
    parent: Swift.String,
  ) throws -> any AsyncSequence<VodStitchDetail, Swift.Error> {
    let request = ListVodStitchDetailsRequest().with {
      $0.parent = parent
    }
    return try self.listVodStitchDetails(byItem: request)
  }

  public func getVodStitchDetail(request: GetVodStitchDetailRequest) async throws
    -> GoogleCloudVideoStitcherV1.VodStitchDetail
  {
    try await self.getVodStitchDetail(request: request, options: .init())
  }

  public func getVodStitchDetail(
    request: GetVodStitchDetailRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudVideoStitcherV1.VodStitchDetail {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getVodStitchDetail(
    name: Swift.String,
  ) async throws -> GoogleCloudVideoStitcherV1.VodStitchDetail {
    let request = GetVodStitchDetailRequest().with {
      $0.name = name
    }
    return try await self.getVodStitchDetail(request: request)
  }

  public func listVodAdTagDetails(request: ListVodAdTagDetailsRequest) async throws
    -> GoogleCloudVideoStitcherV1.ListVodAdTagDetailsResponse
  {
    try await self.listVodAdTagDetails(request: request, options: .init())
  }

  public func listVodAdTagDetails(
    request: ListVodAdTagDetailsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudVideoStitcherV1.ListVodAdTagDetailsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listVodAdTagDetails(
    byItem: ListVodAdTagDetailsRequest
  ) throws -> any AsyncSequence<VodAdTagDetail, Swift.Error> {
    try self.listVodAdTagDetails(byItem: byItem, options: .init())
  }

  public func listVodAdTagDetails(
    byItem: ListVodAdTagDetailsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<VodAdTagDetail, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudVideoStitcherV1.ListVodAdTagDetailsResponse
      in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listVodAdTagDetails(
    parent: Swift.String,
  ) throws -> any AsyncSequence<VodAdTagDetail, Swift.Error> {
    let request = ListVodAdTagDetailsRequest().with {
      $0.parent = parent
    }
    return try self.listVodAdTagDetails(byItem: request)
  }

  public func getVodAdTagDetail(request: GetVodAdTagDetailRequest) async throws
    -> GoogleCloudVideoStitcherV1.VodAdTagDetail
  {
    try await self.getVodAdTagDetail(request: request, options: .init())
  }

  public func getVodAdTagDetail(
    request: GetVodAdTagDetailRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudVideoStitcherV1.VodAdTagDetail {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getVodAdTagDetail(
    name: Swift.String,
  ) async throws -> GoogleCloudVideoStitcherV1.VodAdTagDetail {
    let request = GetVodAdTagDetailRequest().with {
      $0.name = name
    }
    return try await self.getVodAdTagDetail(request: request)
  }

  public func listLiveAdTagDetails(request: ListLiveAdTagDetailsRequest) async throws
    -> GoogleCloudVideoStitcherV1.ListLiveAdTagDetailsResponse
  {
    try await self.listLiveAdTagDetails(request: request, options: .init())
  }

  public func listLiveAdTagDetails(
    request: ListLiveAdTagDetailsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudVideoStitcherV1.ListLiveAdTagDetailsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listLiveAdTagDetails(
    byItem: ListLiveAdTagDetailsRequest
  ) throws -> any AsyncSequence<LiveAdTagDetail, Swift.Error> {
    try self.listLiveAdTagDetails(byItem: byItem, options: .init())
  }

  public func listLiveAdTagDetails(
    byItem: ListLiveAdTagDetailsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<LiveAdTagDetail, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudVideoStitcherV1.ListLiveAdTagDetailsResponse
      in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listLiveAdTagDetails(
    parent: Swift.String,
  ) throws -> any AsyncSequence<LiveAdTagDetail, Swift.Error> {
    let request = ListLiveAdTagDetailsRequest().with {
      $0.parent = parent
    }
    return try self.listLiveAdTagDetails(byItem: request)
  }

  public func getLiveAdTagDetail(request: GetLiveAdTagDetailRequest) async throws
    -> GoogleCloudVideoStitcherV1.LiveAdTagDetail
  {
    try await self.getLiveAdTagDetail(request: request, options: .init())
  }

  public func getLiveAdTagDetail(
    request: GetLiveAdTagDetailRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudVideoStitcherV1.LiveAdTagDetail {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getLiveAdTagDetail(
    name: Swift.String,
  ) async throws -> GoogleCloudVideoStitcherV1.LiveAdTagDetail {
    let request = GetLiveAdTagDetailRequest().with {
      $0.name = name
    }
    return try await self.getLiveAdTagDetail(request: request)
  }

  public func createSlate(request: CreateSlateRequest) async throws -> GoogleLongRunning.Operation {
    try await self.createSlate(request: request, options: .init())
  }

  public func createSlate(
    request: CreateSlateRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func createSlate(withPolling: CreateSlateRequest) async throws -> any GoogleCloudGax
    .PollableOperation<Slate>
  {
    try await self.createSlate(withPolling: withPolling, options: .init())
  }

  public func createSlate(
    withPolling: CreateSlateRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Slate> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Slate>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func createSlate(
    parent: Swift.String,
    slate: Slate?,
    slateId: Swift.String,
  ) async throws -> any GoogleCloudGax.PollableOperation<Slate> {
    let request = CreateSlateRequest().with {
      $0.parent = parent
      $0.slate = slate
      $0.slateId = slateId
    }
    return try await self.createSlate(withPolling: request)
  }

  public func listSlates(request: ListSlatesRequest) async throws
    -> GoogleCloudVideoStitcherV1.ListSlatesResponse
  {
    try await self.listSlates(request: request, options: .init())
  }

  public func listSlates(
    request: ListSlatesRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudVideoStitcherV1.ListSlatesResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listSlates(
    byItem: ListSlatesRequest
  ) throws -> any AsyncSequence<Slate, Swift.Error> {
    try self.listSlates(byItem: byItem, options: .init())
  }

  public func listSlates(
    byItem: ListSlatesRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Slate, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudVideoStitcherV1.ListSlatesResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listSlates(
    parent: Swift.String,
  ) throws -> any AsyncSequence<Slate, Swift.Error> {
    let request = ListSlatesRequest().with {
      $0.parent = parent
    }
    return try self.listSlates(byItem: request)
  }

  public func getSlate(request: GetSlateRequest) async throws -> GoogleCloudVideoStitcherV1.Slate {
    try await self.getSlate(request: request, options: .init())
  }

  public func getSlate(
    request: GetSlateRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudVideoStitcherV1.Slate {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getSlate(
    name: Swift.String,
  ) async throws -> GoogleCloudVideoStitcherV1.Slate {
    let request = GetSlateRequest().with {
      $0.name = name
    }
    return try await self.getSlate(request: request)
  }

  public func updateSlate(request: UpdateSlateRequest) async throws -> GoogleLongRunning.Operation {
    try await self.updateSlate(request: request, options: .init())
  }

  public func updateSlate(
    request: UpdateSlateRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func updateSlate(withPolling: UpdateSlateRequest) async throws -> any GoogleCloudGax
    .PollableOperation<Slate>
  {
    try await self.updateSlate(withPolling: withPolling, options: .init())
  }

  public func updateSlate(
    withPolling: UpdateSlateRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Slate> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Slate>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func updateSlate(
    slate: Slate?,
    updateMask: GoogleCloudWkt.FieldMask?,
  ) async throws -> any GoogleCloudGax.PollableOperation<Slate> {
    let request = UpdateSlateRequest().with {
      $0.slate = slate
      $0.updateMask = updateMask
    }
    return try await self.updateSlate(withPolling: request)
  }

  public func deleteSlate(request: DeleteSlateRequest) async throws -> GoogleLongRunning.Operation {
    try await self.deleteSlate(request: request, options: .init())
  }

  public func deleteSlate(
    request: DeleteSlateRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteSlate(withPolling: DeleteSlateRequest) async throws -> any GoogleCloudGax
    .PollableOperation<Swift.Void>
  {
    try await self.deleteSlate(withPolling: withPolling, options: .init())
  }

  public func deleteSlate(
    withPolling: DeleteSlateRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Swift.Void> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Swift.Void>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func deleteSlate(
    name: Swift.String,
  ) async throws -> any GoogleCloudGax.PollableOperation<Swift.Void> {
    let request = DeleteSlateRequest().with {
      $0.name = name
    }
    return try await self.deleteSlate(withPolling: request)
  }

  public func createLiveSession(request: CreateLiveSessionRequest) async throws
    -> GoogleCloudVideoStitcherV1.LiveSession
  {
    try await self.createLiveSession(request: request, options: .init())
  }

  public func createLiveSession(
    request: CreateLiveSessionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudVideoStitcherV1.LiveSession {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func createLiveSession(
    parent: Swift.String,
    liveSession: LiveSession?,
  ) async throws -> GoogleCloudVideoStitcherV1.LiveSession {
    let request = CreateLiveSessionRequest().with {
      $0.parent = parent
      $0.liveSession = liveSession
    }
    return try await self.createLiveSession(request: request)
  }

  public func getLiveSession(request: GetLiveSessionRequest) async throws
    -> GoogleCloudVideoStitcherV1.LiveSession
  {
    try await self.getLiveSession(request: request, options: .init())
  }

  public func getLiveSession(
    request: GetLiveSessionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudVideoStitcherV1.LiveSession {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getLiveSession(
    name: Swift.String,
  ) async throws -> GoogleCloudVideoStitcherV1.LiveSession {
    let request = GetLiveSessionRequest().with {
      $0.name = name
    }
    return try await self.getLiveSession(request: request)
  }

  public func createLiveConfig(request: CreateLiveConfigRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.createLiveConfig(request: request, options: .init())
  }

  public func createLiveConfig(
    request: CreateLiveConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func createLiveConfig(withPolling: CreateLiveConfigRequest) async throws
    -> any GoogleCloudGax.PollableOperation<LiveConfig>
  {
    try await self.createLiveConfig(withPolling: withPolling, options: .init())
  }

  public func createLiveConfig(
    withPolling: CreateLiveConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<LiveConfig> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<LiveConfig>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func createLiveConfig(
    parent: Swift.String,
    liveConfig: LiveConfig?,
    liveConfigId: Swift.String,
  ) async throws -> any GoogleCloudGax.PollableOperation<LiveConfig> {
    let request = CreateLiveConfigRequest().with {
      $0.parent = parent
      $0.liveConfig = liveConfig
      $0.liveConfigId = liveConfigId
    }
    return try await self.createLiveConfig(withPolling: request)
  }

  public func listLiveConfigs(request: ListLiveConfigsRequest) async throws
    -> GoogleCloudVideoStitcherV1.ListLiveConfigsResponse
  {
    try await self.listLiveConfigs(request: request, options: .init())
  }

  public func listLiveConfigs(
    request: ListLiveConfigsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudVideoStitcherV1.ListLiveConfigsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listLiveConfigs(
    byItem: ListLiveConfigsRequest
  ) throws -> any AsyncSequence<LiveConfig, Swift.Error> {
    try self.listLiveConfigs(byItem: byItem, options: .init())
  }

  public func listLiveConfigs(
    byItem: ListLiveConfigsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<LiveConfig, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudVideoStitcherV1.ListLiveConfigsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listLiveConfigs(
    parent: Swift.String,
  ) throws -> any AsyncSequence<LiveConfig, Swift.Error> {
    let request = ListLiveConfigsRequest().with {
      $0.parent = parent
    }
    return try self.listLiveConfigs(byItem: request)
  }

  public func getLiveConfig(request: GetLiveConfigRequest) async throws
    -> GoogleCloudVideoStitcherV1.LiveConfig
  {
    try await self.getLiveConfig(request: request, options: .init())
  }

  public func getLiveConfig(
    request: GetLiveConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudVideoStitcherV1.LiveConfig {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getLiveConfig(
    name: Swift.String,
  ) async throws -> GoogleCloudVideoStitcherV1.LiveConfig {
    let request = GetLiveConfigRequest().with {
      $0.name = name
    }
    return try await self.getLiveConfig(request: request)
  }

  public func deleteLiveConfig(request: DeleteLiveConfigRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.deleteLiveConfig(request: request, options: .init())
  }

  public func deleteLiveConfig(
    request: DeleteLiveConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteLiveConfig(withPolling: DeleteLiveConfigRequest) async throws
    -> any GoogleCloudGax.PollableOperation<Swift.Void>
  {
    try await self.deleteLiveConfig(withPolling: withPolling, options: .init())
  }

  public func deleteLiveConfig(
    withPolling: DeleteLiveConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Swift.Void> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Swift.Void>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func deleteLiveConfig(
    name: Swift.String,
  ) async throws -> any GoogleCloudGax.PollableOperation<Swift.Void> {
    let request = DeleteLiveConfigRequest().with {
      $0.name = name
    }
    return try await self.deleteLiveConfig(withPolling: request)
  }

  public func updateLiveConfig(request: UpdateLiveConfigRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.updateLiveConfig(request: request, options: .init())
  }

  public func updateLiveConfig(
    request: UpdateLiveConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func updateLiveConfig(withPolling: UpdateLiveConfigRequest) async throws
    -> any GoogleCloudGax.PollableOperation<LiveConfig>
  {
    try await self.updateLiveConfig(withPolling: withPolling, options: .init())
  }

  public func updateLiveConfig(
    withPolling: UpdateLiveConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<LiveConfig> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<LiveConfig>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func updateLiveConfig(
    liveConfig: LiveConfig?,
    updateMask: GoogleCloudWkt.FieldMask?,
  ) async throws -> any GoogleCloudGax.PollableOperation<LiveConfig> {
    let request = UpdateLiveConfigRequest().with {
      $0.liveConfig = liveConfig
      $0.updateMask = updateMask
    }
    return try await self.updateLiveConfig(withPolling: request)
  }

  public func createVodConfig(request: CreateVodConfigRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.createVodConfig(request: request, options: .init())
  }

  public func createVodConfig(
    request: CreateVodConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func createVodConfig(withPolling: CreateVodConfigRequest) async throws
    -> any GoogleCloudGax.PollableOperation<VodConfig>
  {
    try await self.createVodConfig(withPolling: withPolling, options: .init())
  }

  public func createVodConfig(
    withPolling: CreateVodConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<VodConfig> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<VodConfig>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func createVodConfig(
    parent: Swift.String,
    vodConfig: VodConfig?,
    vodConfigId: Swift.String,
  ) async throws -> any GoogleCloudGax.PollableOperation<VodConfig> {
    let request = CreateVodConfigRequest().with {
      $0.parent = parent
      $0.vodConfig = vodConfig
      $0.vodConfigId = vodConfigId
    }
    return try await self.createVodConfig(withPolling: request)
  }

  public func listVodConfigs(request: ListVodConfigsRequest) async throws
    -> GoogleCloudVideoStitcherV1.ListVodConfigsResponse
  {
    try await self.listVodConfigs(request: request, options: .init())
  }

  public func listVodConfigs(
    request: ListVodConfigsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudVideoStitcherV1.ListVodConfigsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listVodConfigs(
    byItem: ListVodConfigsRequest
  ) throws -> any AsyncSequence<VodConfig, Swift.Error> {
    try self.listVodConfigs(byItem: byItem, options: .init())
  }

  public func listVodConfigs(
    byItem: ListVodConfigsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<VodConfig, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudVideoStitcherV1.ListVodConfigsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listVodConfigs(
    parent: Swift.String,
  ) throws -> any AsyncSequence<VodConfig, Swift.Error> {
    let request = ListVodConfigsRequest().with {
      $0.parent = parent
    }
    return try self.listVodConfigs(byItem: request)
  }

  public func getVodConfig(request: GetVodConfigRequest) async throws
    -> GoogleCloudVideoStitcherV1.VodConfig
  {
    try await self.getVodConfig(request: request, options: .init())
  }

  public func getVodConfig(
    request: GetVodConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudVideoStitcherV1.VodConfig {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getVodConfig(
    name: Swift.String,
  ) async throws -> GoogleCloudVideoStitcherV1.VodConfig {
    let request = GetVodConfigRequest().with {
      $0.name = name
    }
    return try await self.getVodConfig(request: request)
  }

  public func deleteVodConfig(request: DeleteVodConfigRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.deleteVodConfig(request: request, options: .init())
  }

  public func deleteVodConfig(
    request: DeleteVodConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteVodConfig(withPolling: DeleteVodConfigRequest) async throws
    -> any GoogleCloudGax.PollableOperation<Swift.Void>
  {
    try await self.deleteVodConfig(withPolling: withPolling, options: .init())
  }

  public func deleteVodConfig(
    withPolling: DeleteVodConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Swift.Void> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Swift.Void>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func deleteVodConfig(
    name: Swift.String,
  ) async throws -> any GoogleCloudGax.PollableOperation<Swift.Void> {
    let request = DeleteVodConfigRequest().with {
      $0.name = name
    }
    return try await self.deleteVodConfig(withPolling: request)
  }

  public func updateVodConfig(request: UpdateVodConfigRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.updateVodConfig(request: request, options: .init())
  }

  public func updateVodConfig(
    request: UpdateVodConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func updateVodConfig(withPolling: UpdateVodConfigRequest) async throws
    -> any GoogleCloudGax.PollableOperation<VodConfig>
  {
    try await self.updateVodConfig(withPolling: withPolling, options: .init())
  }

  public func updateVodConfig(
    withPolling: UpdateVodConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<VodConfig> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<VodConfig>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func updateVodConfig(
    vodConfig: VodConfig?,
    updateMask: GoogleCloudWkt.FieldMask?,
  ) async throws -> any GoogleCloudGax.PollableOperation<VodConfig> {
    let request = UpdateVodConfigRequest().with {
      $0.vodConfig = vodConfig
      $0.updateMask = updateMask
    }
    return try await self.updateVodConfig(withPolling: request)
  }

  public func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
    -> GoogleLongRunning.ListOperationsResponse
  {
    try await self.listOperations(request: request, options: .init())
  }

  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    try self.listOperations(byItem: byItem, options: .init())
  }

  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listOperations(
    name: Swift.String,
    filter: Swift.String,
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let request = GoogleLongRunning.ListOperationsRequest().with {
      $0.name = name
      $0.filter = filter
    }
    return try self.listOperations(byItem: request)
  }

  public func getOperation(request: GoogleLongRunning.GetOperationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.getOperation(request: request, options: .init())
  }

  public func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getOperation(
    name: Swift.String,
  ) async throws -> GoogleLongRunning.Operation {
    let request = GoogleLongRunning.GetOperationRequest().with {
      $0.name = name
    }
    return try await self.getOperation(request: request)
  }

  public func deleteOperation(request: GoogleLongRunning.DeleteOperationRequest) async throws {
    try await self.deleteOperation(request: request, options: .init())
  }

  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.DeleteOperationRequest().with {
      $0.name = name
    }
    try await self.deleteOperation(request: request)
  }

  public func cancelOperation(request: GoogleLongRunning.CancelOperationRequest) async throws {
    try await self.cancelOperation(request: request, options: .init())
  }

  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func cancelOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.CancelOperationRequest().with {
      $0.name = name
    }
    try await self.cancelOperation(request: request)
  }
}
