// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWkt
import GoogleLongRunning
import GoogleRpc
import GoogleCloudGax

extension Clients {
  final class VideoStitcherServiceRetry: VideoStitcherServiceStub {
    let inner: any VideoStitcherServiceStub
    let options: GoogleCloudGax.ClientOptions

    public init(_ inner: any VideoStitcherServiceStub, options: GoogleCloudGax.ClientOptions) {
      self.inner = inner
      self.options = options
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleCloudGax.RequestOptions,
      idempotent: Swift.Bool,
      action: (Input, GoogleCloudGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      let loop = GoogleCloudGax._RetryLoop(
        options: options, withDefault: self.options, idempotent: idempotent,
      )
      let attempt = { (attemptTimeout: Swift.Duration?) async throws -> Output in
        var attemptOptions = options
        attemptOptions.attemptTimeout = attemptTimeout
        return try await action(request, attemptOptions)
      }
      return try await loop.run(attempt: attempt)
    }

    public func createCdnKey(
      request: CreateCdnKeyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateCdnKeyRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createCdnKey(request: r, options: o)
        })
    }

    public func listCdnKeys(
      request: ListCdnKeysRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudVideoStitcherV1.ListCdnKeysResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListCdnKeysRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudVideoStitcherV1.ListCdnKeysResponse
          in
          return try await self.inner.listCdnKeys(request: r, options: o)
        })
    }

    public func getCdnKey(
      request: GetCdnKeyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudVideoStitcherV1.CdnKey {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetCdnKeyRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudVideoStitcherV1.CdnKey
          in
          return try await self.inner.getCdnKey(request: r, options: o)
        })
    }

    public func deleteCdnKey(
      request: DeleteCdnKeyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteCdnKeyRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteCdnKey(request: r, options: o)
        })
    }

    public func updateCdnKey(
      request: UpdateCdnKeyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateCdnKeyRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateCdnKey(request: r, options: o)
        })
    }

    public func createVodSession(
      request: CreateVodSessionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudVideoStitcherV1.VodSession {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateVodSessionRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudVideoStitcherV1.VodSession
          in
          return try await self.inner.createVodSession(request: r, options: o)
        })
    }

    public func getVodSession(
      request: GetVodSessionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudVideoStitcherV1.VodSession {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetVodSessionRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudVideoStitcherV1.VodSession
          in
          return try await self.inner.getVodSession(request: r, options: o)
        })
    }

    public func listVodStitchDetails(
      request: ListVodStitchDetailsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudVideoStitcherV1.ListVodStitchDetailsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListVodStitchDetailsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudVideoStitcherV1.ListVodStitchDetailsResponse
          in
          return try await self.inner.listVodStitchDetails(request: r, options: o)
        })
    }

    public func getVodStitchDetail(
      request: GetVodStitchDetailRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudVideoStitcherV1.VodStitchDetail {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetVodStitchDetailRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudVideoStitcherV1.VodStitchDetail
          in
          return try await self.inner.getVodStitchDetail(request: r, options: o)
        })
    }

    public func listVodAdTagDetails(
      request: ListVodAdTagDetailsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudVideoStitcherV1.ListVodAdTagDetailsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListVodAdTagDetailsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudVideoStitcherV1.ListVodAdTagDetailsResponse
          in
          return try await self.inner.listVodAdTagDetails(request: r, options: o)
        })
    }

    public func getVodAdTagDetail(
      request: GetVodAdTagDetailRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudVideoStitcherV1.VodAdTagDetail {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetVodAdTagDetailRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudVideoStitcherV1.VodAdTagDetail
          in
          return try await self.inner.getVodAdTagDetail(request: r, options: o)
        })
    }

    public func listLiveAdTagDetails(
      request: ListLiveAdTagDetailsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudVideoStitcherV1.ListLiveAdTagDetailsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListLiveAdTagDetailsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudVideoStitcherV1.ListLiveAdTagDetailsResponse
          in
          return try await self.inner.listLiveAdTagDetails(request: r, options: o)
        })
    }

    public func getLiveAdTagDetail(
      request: GetLiveAdTagDetailRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudVideoStitcherV1.LiveAdTagDetail {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetLiveAdTagDetailRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudVideoStitcherV1.LiveAdTagDetail
          in
          return try await self.inner.getLiveAdTagDetail(request: r, options: o)
        })
    }

    public func createSlate(
      request: CreateSlateRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateSlateRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createSlate(request: r, options: o)
        })
    }

    public func listSlates(
      request: ListSlatesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudVideoStitcherV1.ListSlatesResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListSlatesRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudVideoStitcherV1.ListSlatesResponse
          in
          return try await self.inner.listSlates(request: r, options: o)
        })
    }

    public func getSlate(
      request: GetSlateRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudVideoStitcherV1.Slate {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetSlateRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudVideoStitcherV1.Slate
          in
          return try await self.inner.getSlate(request: r, options: o)
        })
    }

    public func updateSlate(
      request: UpdateSlateRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateSlateRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateSlate(request: r, options: o)
        })
    }

    public func deleteSlate(
      request: DeleteSlateRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteSlateRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteSlate(request: r, options: o)
        })
    }

    public func createLiveSession(
      request: CreateLiveSessionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudVideoStitcherV1.LiveSession {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateLiveSessionRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudVideoStitcherV1.LiveSession
          in
          return try await self.inner.createLiveSession(request: r, options: o)
        })
    }

    public func getLiveSession(
      request: GetLiveSessionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudVideoStitcherV1.LiveSession {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetLiveSessionRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudVideoStitcherV1.LiveSession
          in
          return try await self.inner.getLiveSession(request: r, options: o)
        })
    }

    public func createLiveConfig(
      request: CreateLiveConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateLiveConfigRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createLiveConfig(request: r, options: o)
        })
    }

    public func listLiveConfigs(
      request: ListLiveConfigsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudVideoStitcherV1.ListLiveConfigsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListLiveConfigsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudVideoStitcherV1.ListLiveConfigsResponse
          in
          return try await self.inner.listLiveConfigs(request: r, options: o)
        })
    }

    public func getLiveConfig(
      request: GetLiveConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudVideoStitcherV1.LiveConfig {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetLiveConfigRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudVideoStitcherV1.LiveConfig
          in
          return try await self.inner.getLiveConfig(request: r, options: o)
        })
    }

    public func deleteLiveConfig(
      request: DeleteLiveConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteLiveConfigRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteLiveConfig(request: r, options: o)
        })
    }

    public func updateLiveConfig(
      request: UpdateLiveConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateLiveConfigRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateLiveConfig(request: r, options: o)
        })
    }

    public func createVodConfig(
      request: CreateVodConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateVodConfigRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createVodConfig(request: r, options: o)
        })
    }

    public func listVodConfigs(
      request: ListVodConfigsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudVideoStitcherV1.ListVodConfigsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListVodConfigsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudVideoStitcherV1.ListVodConfigsResponse
          in
          return try await self.inner.listVodConfigs(request: r, options: o)
        })
    }

    public func getVodConfig(
      request: GetVodConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudVideoStitcherV1.VodConfig {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetVodConfigRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudVideoStitcherV1.VodConfig
          in
          return try await self.inner.getVodConfig(request: r, options: o)
        })
    }

    public func deleteVodConfig(
      request: DeleteVodConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteVodConfigRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteVodConfig(request: r, options: o)
        })
    }

    public func updateVodConfig(
      request: UpdateVodConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateVodConfigRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateVodConfig(request: r, options: o)
        })
    }

    public func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleLongRunning.ListOperationsRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> GoogleLongRunning.ListOperationsResponse
          in
          return try await self.inner.listOperations(request: r, options: o)
        })
    }

    public func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleLongRunning.GetOperationRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.getOperation(request: r, options: o)
        })
    }

    public func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: GoogleLongRunning.DeleteOperationRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> Void in
          return try await self.inner.deleteOperation(request: r, options: o)
        })
    }

    public func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: GoogleLongRunning.CancelOperationRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> Void in
          return try await self.inner.cancelOperation(request: r, options: o)
        })
    }
  }
}
