// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// Metadata for an inserted ad break.
public struct VodSessionAdBreak: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// List of events that are expected to be triggered, ordered by time.
  public var progressEvents: [ProgressEvent] = []

  /// Ordered list of ads stitched into the ad break.
  public var ads: [VodSessionAd] = []

  /// Ad break end time in seconds relative to the start of the VOD asset.
  public var endTimeOffset: GoogleWKT.Duration? = nil

  /// Ad break start time in seconds relative to the start of the VOD asset.
  public var startTimeOffset: GoogleWKT.Duration? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `VodSessionAdBreak`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = VodSessionAdBreak().with { $0.progressEvents = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let progressEvents = CodingKeys(stringValue: "progressEvents")
    static let ads = CodingKeys(stringValue: "ads")
    static let endTimeOffset = CodingKeys(stringValue: "endTimeOffset")
    static let startTimeOffset = CodingKeys(stringValue: "startTimeOffset")

    static let _knownKeys: Set<Swift.String> = [
      "progressEvents",
      "ads",
      "endTimeOffset",
      "startTimeOffset",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent([ProgressEvent].self, forKey: .progressEvents) {
      self.progressEvents = value
    }
    if let value = try container.decodeIfPresent([VodSessionAd].self, forKey: .ads) {
      self.ads = value
    }
    self.endTimeOffset = try container.decodeIfPresent(
      GoogleWKT.Duration.self, forKey: .endTimeOffset)
    self.startTimeOffset = try container.decodeIfPresent(
      GoogleWKT.Duration.self, forKey: .startTimeOffset)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.progressEvents, forKey: .progressEvents)
    try container.encode(self.ads, forKey: .ads)
    try container.encodeIfPresent(self.endTimeOffset, forKey: .endTimeOffset)
    try container.encodeIfPresent(self.startTimeOffset, forKey: .startTimeOffset)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.video.stitcher.v1.VodSessionAdBreak"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
