// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// Metadata for a VOD session. The session expires 4 hours after its creation.
public struct VodSession: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Output only. The name of the VOD session, in the form of
  /// `projects/{project_number}/locations/{location}/vodSessions/{id}`.
  public var name: Swift.String = Swift.String()

  /// Output only. Metadata of what was stitched into the content.
  public var interstitials: Interstitials? = nil

  /// Output only. The playback URI of the stitched content.
  public var playUri: Swift.String = Swift.String()

  /// URI of the media to stitch. For most use cases, you should create a
  /// [VodConfig][google.cloud.video.stitcher.v1.VodConfig] with this information
  /// rather than setting this field directly.
  ///
  /// [google.cloud.video.stitcher.v1.VodConfig]: <doc:VodConfig>
  public var sourceUri: Swift.String = Swift.String()

  /// Ad tag URI. For most use cases, you should create a
  /// [VodConfig][google.cloud.video.stitcher.v1.VodConfig] with this information
  /// rather than setting this field directly.
  ///
  /// [google.cloud.video.stitcher.v1.VodConfig]: <doc:VodConfig>
  public var adTagUri: Swift.String = Swift.String()

  /// Key value pairs for ad tag macro replacement, only available for VOD
  /// sessions that do not implement Google Ad manager ad insertion. If the
  /// specified ad tag URI has macros, this field provides the mapping to the
  /// value that will replace the macro in the ad tag URI.
  ///
  /// Macros are designated by square brackets, for example:
  ///
  ///   Ad tag URI: `"https://doubleclick.google.com/ad/1?geo_id=[geoId]"`
  ///
  ///   Ad tag macro map: `{"geoId": "123"}`
  ///
  ///   Fully qualified ad tag:
  ///   `"https://doubleclick.google.com/ad/1?geo_id=123"`
  public var adTagMacroMap: [Swift.String: Swift.String] = [:]

  /// Additional options that affect the output of the manifest.
  public var manifestOptions: ManifestOptions? = nil

  /// Output only. The generated ID of the VodSession's source media.
  public var assetId: Swift.String = Swift.String()

  /// Required. Determines how the ad should be tracked.
  public var adTracking: AdTracking = AdTracking()

  /// This field should be set with appropriate values if GAM is being used for
  /// ads.
  public var gamSettings: VodSession.GamSettings? = nil

  /// The resource name of the VOD config for this session, in the form of
  /// `projects/{project}/locations/{location}/vodConfigs/{id}`.
  public var vodConfig: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `VodSession`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = VodSession().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let interstitials = CodingKeys(stringValue: "interstitials")
    static let playUri = CodingKeys(stringValue: "playUri")
    static let sourceUri = CodingKeys(stringValue: "sourceUri")
    static let adTagUri = CodingKeys(stringValue: "adTagUri")
    static let adTagMacroMap = CodingKeys(stringValue: "adTagMacroMap")
    static let manifestOptions = CodingKeys(stringValue: "manifestOptions")
    static let assetId = CodingKeys(stringValue: "assetId")
    static let adTracking = CodingKeys(stringValue: "adTracking")
    static let gamSettings = CodingKeys(stringValue: "gamSettings")
    static let vodConfig = CodingKeys(stringValue: "vodConfig")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "interstitials",
      "playUri",
      "sourceUri",
      "adTagUri",
      "adTagMacroMap",
      "manifestOptions",
      "assetId",
      "adTracking",
      "gamSettings",
      "vodConfig",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    self.interstitials = try container.decodeIfPresent(Interstitials.self, forKey: .interstitials)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .playUri) {
      self.playUri = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .sourceUri) {
      self.sourceUri = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .adTagUri) {
      self.adTagUri = value
    }
    if let value = try container.decodeIfPresent(
      [Swift.String: Swift.String].self, forKey: .adTagMacroMap)
    {
      self.adTagMacroMap = value
    }
    self.manifestOptions = try container.decodeIfPresent(
      ManifestOptions.self, forKey: .manifestOptions)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .assetId) {
      self.assetId = value
    }
    if let value = try container.decodeIfPresent(AdTracking.self, forKey: .adTracking) {
      self.adTracking = value
    }
    self.gamSettings = try container.decodeIfPresent(
      VodSession.GamSettings.self, forKey: .gamSettings)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .vodConfig) {
      self.vodConfig = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encodeIfPresent(self.interstitials, forKey: .interstitials)
    try container.encode(self.playUri, forKey: .playUri)
    try container.encode(self.sourceUri, forKey: .sourceUri)
    try container.encode(self.adTagUri, forKey: .adTagUri)
    try container.encode(self.adTagMacroMap, forKey: .adTagMacroMap)
    try container.encodeIfPresent(self.manifestOptions, forKey: .manifestOptions)
    try container.encode(self.assetId, forKey: .assetId)
    try container.encode(self.adTracking, forKey: .adTracking)
    try container.encodeIfPresent(self.gamSettings, forKey: .gamSettings)
    try container.encode(self.vodConfig, forKey: .vodConfig)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Defines fields related to Google Ad Manager (GAM). This should be set if
  /// GAM is being used for ads.
  public struct GamSettings: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Required. Ad Manager network code.
    public var networkCode: Swift.String = Swift.String()

    /// Required. The stream ID generated by Ad Manager.
    public var streamId: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `GamSettings`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = GamSettings().with { $0.networkCode = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let networkCode = CodingKeys(stringValue: "networkCode")
      static let streamId = CodingKeys(stringValue: "streamId")

      static let _knownKeys: Set<Swift.String> = [
        "networkCode",
        "streamId",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .networkCode) {
        self.networkCode = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .streamId) {
        self.streamId = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.networkCode, forKey: .networkCode)
      try container.encode(self.streamId, forKey: .streamId)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.video.stitcher.v1.VodSession.GamSettings"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.video.stitcher.v1.VodSession"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
