// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Metadata for a VOD session. The session expires 4 hours after its creation.
public struct VodSession: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Output only. The name of the VOD session, in the form of
  /// `projects/{project_number}/locations/{location}/vodSessions/{id}`.
  public var name: Swift.String = Swift.String()

  /// Output only. Metadata of what was stitched into the content.
  public var interstitials: Interstitials? = nil

  /// Output only. The playback URI of the stitched content.
  public var playUri: Swift.String = Swift.String()

  /// URI of the media to stitch. For most use cases, you should create a
  /// [VodConfig][google.cloud.video.stitcher.v1.VodConfig] with this information
  /// rather than setting this field directly.
  ///
  /// [google.cloud.video.stitcher.v1.VodConfig]: <doc:VodConfig>
  public var sourceUri: Swift.String = Swift.String()

  /// Ad tag URI. For most use cases, you should create a
  /// [VodConfig][google.cloud.video.stitcher.v1.VodConfig] with this information
  /// rather than setting this field directly.
  ///
  /// [google.cloud.video.stitcher.v1.VodConfig]: <doc:VodConfig>
  public var adTagUri: Swift.String = Swift.String()

  /// Key value pairs for ad tag macro replacement, only available for VOD
  /// sessions that do not implement Google Ad manager ad insertion. If the
  /// specified ad tag URI has macros, this field provides the mapping to the
  /// value that will replace the macro in the ad tag URI.
  ///
  /// Macros are designated by square brackets, for example:
  ///
  ///   Ad tag URI: `"https://doubleclick.google.com/ad/1?geo_id=[geoId]"`
  ///
  ///   Ad tag macro map: `{"geoId": "123"}`
  ///
  ///   Fully qualified ad tag:
  ///   `"https://doubleclick.google.com/ad/1?geo_id=123"`
  public var adTagMacroMap: [Swift.String: Swift.String] = [:]

  /// Additional options that affect the output of the manifest.
  public var manifestOptions: ManifestOptions? = nil

  /// Output only. The generated ID of the VodSession's source media.
  public var assetId: Swift.String = Swift.String()

  /// Required. Determines how the ad should be tracked.
  public var adTracking: AdTracking = AdTracking()

  /// This field should be set with appropriate values if GAM is being used for
  /// ads.
  public var gamSettings: VodSession.GamSettings? = nil

  /// The resource name of the VOD config for this session, in the form of
  /// `projects/{project}/locations/{location}/vodConfigs/{id}`.
  public var vodConfig: Swift.String = Swift.String()

  /// Initialize a new instance of `VodSession`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = VodSession().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Defines fields related to Google Ad Manager (GAM). This should be set if
  /// GAM is being used for ads.
  public struct GamSettings: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Required. Ad Manager network code.
    public var networkCode: Swift.String = Swift.String()

    /// Required. The stream ID generated by Ad Manager.
    public var streamId: Swift.String = Swift.String()

    /// Initialize a new instance of `GamSettings`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = GamSettings().with { $0.networkCode = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.video.stitcher.v1.VodSession.GamSettings"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.video.stitcher.v1.VodSession"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
